"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Plus } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button, Checkbox, DateControl, ErrorState, Field, FilterBar, LoadingSkeleton, Modal, PageHeader, Pagination, Search, Select, StatusBadge, Table, Textarea, type TableColumn } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { api, errorMessage, queryString } from "@/lib/api-client";
import { formatDateTime, formatMinutes } from "@/lib/format";
import { useReferenceData } from "@/lib/reference-data";
import type { Breakdown, Machine, PagedResult } from "@/types/api";

export function BreakdownList(){
 const refs=useReferenceData();const client=useQueryClient();const {showToast}=useToast();const router=useRouter();const [page,setPage]=useState(1);const [open,setOpen]=useState(false);const [form,setForm]=useState({machineId:"",severity:"HIGH",machineStopped:true,description:"",initialObservation:"",supervisorId:""});const [filters,setFilters]=useState({search:"",severity:"",status:"",machineId:"",technicianId:"",supervisorId:"",reportedFrom:"",reportedTo:"",openOnly:"true"});
 const machines=useQuery({queryKey:["machines","breakdown-options"],queryFn:({signal})=>api.get<PagedResult<Machine>>("/machines?Page=1&PageSize=100&IsActive=true",signal)});
 const params=queryString({Search:filters.search,Page:page,PageSize:20,Severity:filters.severity,Status:filters.status,MachineId:filters.machineId,TechnicianId:filters.technicianId,SupervisorId:filters.supervisorId,ReportedFrom:filters.reportedFrom,ReportedTo:filters.reportedTo,OpenOnly:filters.openOnly});
 const breakdowns=useQuery({queryKey:["breakdowns",filters,page],queryFn:({signal})=>api.get<PagedResult<Breakdown>>(`/breakdowns${params}`,signal),placeholderData:(previous)=>previous});
 const create=useMutation({mutationFn:()=>api.post<Breakdown>("/breakdowns",{...form,initialObservation:form.initialObservation||null,supervisorId:form.supervisorId||null}),onSuccess:(created)=>{showToast("Breakdown reported");setOpen(false);client.invalidateQueries({queryKey:["breakdowns"]});router.push(`/breakdowns/${created.id}`)}});
 const set=(name:string,value:string)=>{setFilters((current)=>({...current,[name]:value}));setPage(1)};
 const columns:TableColumn<Breakdown>[]=[{key:"number",header:"Breakdown",cell:(row)=><div className="primary-cell"><strong>{row.breakdownNumber}</strong><span>{row.machineCode} · {row.machineName}</span></div>},{key:"severity",header:"Severity",cell:(row)=><StatusBadge value={row.severity}/>},{key:"reported",header:"Reported",cell:(row)=>formatDateTime(row.reportedAt)},{key:"stopped",header:"Machine stopped",cell:(row)=><StatusBadge value={row.machineStopped?"Stopped":"Running"}/>},{key:"assigned",header:"Technician / supervisor",cell:(row)=><div className="primary-cell"><span>{row.technicianName||"Unassigned"}</span><small>{row.supervisorName}</small></div>},{key:"status",header:"Status",cell:(row)=><StatusBadge value={row.status}/>},{key:"downtime",header:"Downtime",cell:(row)=><div className="primary-cell"><span>{formatMinutes(row.downtimeMinutes)}</span>{row.downtimeOngoing&&<small>Ongoing</small>}</div>},{key:"action",header:"",cell:(row)=><Link className="icon-button" href={`/breakdowns/${row.id}`} aria-label={`View ${row.breakdownNumber}`}><Eye size={16}/></Link>}];
 return <div className="page-stack"><PageHeader eyebrow="Corrective maintenance" title="Breakdowns" description="Track incidents, response, corrective work, approvals, and downtime." actions={<Button onClick={()=>setOpen(true)}><Plus size={16}/> Report breakdown</Button>}/><FilterBar onClear={()=>setFilters({search:"",severity:"",status:"",machineId:"",technicianId:"",supervisorId:"",reportedFrom:"",reportedTo:"",openOnly:""})}><Search value={filters.search} onChange={(event)=>set("search",event.target.value)} placeholder="Number, machine or description…"/><Select aria-label="Severity" value={filters.severity} onChange={(event)=>set("severity",event.target.value)}><option value="">All severities</option>{["LOW","MEDIUM","HIGH","CRITICAL"].map((value)=><option key={value}>{value}</option>)}</Select><Select aria-label="Status" value={filters.status} onChange={(event)=>set("status",event.target.value)}><option value="">All statuses</option>{["REPORTED","ASSIGNED","IN_PROGRESS","AWAITING_APPROVAL","REJECTED","CLOSED","CANCELLED"].map((value)=><option key={value}>{value}</option>)}</Select><Select aria-label="Machine" value={filters.machineId} onChange={(event)=>set("machineId",event.target.value)}><option value="">All machines</option>{machines.data?.items.map((item)=><option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select><Select aria-label="Open state" value={filters.openOnly} onChange={(event)=>set("openOnly",event.target.value)}><option value="">All records</option><option value="true">Open only</option></Select><DateControl aria-label="Reported from" value={filters.reportedFrom} onChange={(event)=>set("reportedFrom",event.target.value)}/><DateControl aria-label="Reported to" value={filters.reportedTo} onChange={(event)=>set("reportedTo",event.target.value)}/></FilterBar>{breakdowns.isPending?<LoadingSkeleton rows={8}/>:breakdowns.error?<ErrorState error={breakdowns.error} onRetry={()=>breakdowns.refetch()}/>:<><Table columns={columns} items={breakdowns.data?.items??[]} rowKey={(row)=>row.id}/><Pagination page={breakdowns.data?.page??page} totalPages={breakdowns.data?.totalPages??1} totalCount={breakdowns.data?.totalCount} onPageChange={setPage}/></>}
 <Modal open={open} title="Report a breakdown" onClose={()=>setOpen(false)} size="lg" footer={<><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={create.isPending} disabled={!form.machineId||!form.description.trim()} onClick={()=>create.mutate()}>Report breakdown</Button></>}><div className="form-grid"><Field label="Machine" required><Select value={form.machineId} onChange={(event)=>setForm({...form,machineId:event.target.value})}><option value="">Select machine</option>{machines.data?.items.map((item)=><option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select></Field><Field label="Severity"><Select value={form.severity} onChange={(event)=>setForm({...form,severity:event.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map((value)=><option key={value}>{value}</option>)}</Select></Field><Field label="Supervisor"><Select value={form.supervisorId} onChange={(event)=>setForm({...form,supervisorId:event.target.value})}><option value="">Use machine supervisor</option>{refs.supervisors.data?.map((item)=><option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</Select></Field><Checkbox label="Machine stopped" checked={form.machineStopped} onChange={(event)=>setForm({...form,machineStopped:event.target.checked})}/><Field className="field-span" label="Description" required><Textarea rows={4} value={form.description} onChange={(event)=>setForm({...form,description:event.target.value})}/></Field><Field className="field-span" label="Initial observation"><Textarea rows={3} value={form.initialObservation} onChange={(event)=>setForm({...form,initialObservation:event.target.value})}/></Field></div>{create.error&&<p className="field-error">{errorMessage(create.error)}</p>}</Modal></div>
}
