"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, RotateCcw, UserRoundCog, XCircle } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Button, Card, EmptyState, ErrorState, Field, FileAction, Input, LoadingSkeleton, Modal, PageHeader, SectionHeader, Select, StatusBadge, Tabs, Textarea } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { useAuth } from "@/features/auth/auth-provider";
import { api, errorMessage } from "@/lib/api-client";
import { formatDateTime, formatMinutes } from "@/lib/format";
import { useReferenceData } from "@/lib/reference-data";
import type { Breakdown, CorrectiveExecution, FileAttachment, TimelineEvent } from "@/types/api";

interface BreakdownAssignment { id:string;sequenceNumber:number;technicianName:string;supervisorName:string;assignedAt:string;reason?:string|null }
interface CorrectiveSubmission { id:string;versionNumber:number;technicianName:string;submittedAt:string;durationMinutes:number;review?:{decision:string;supervisorName:string;decisionAt:string;remarks?:string|null}|null }

export function BreakdownDetailView({id}:{id:string}){
 const {hasRole}=useAuth();const refs=useReferenceData();const client=useQueryClient();const {showToast}=useToast();const [tab,setTab]=useState("breakdown");const [assignOpen,setAssignOpen]=useState(false);const [technicianId,setTechnicianId]=useState("");const [supervisorId,setSupervisorId]=useState("");const [reason,setReason]=useState("");const [returnOpen,setReturnOpen]=useState(false);const [returnRemarks,setReturnRemarks]=useState("");const [review,setReview]=useState<"approve"|"reject">();const [reviewRemarks,setReviewRemarks]=useState("");
 const detail=useQuery({queryKey:["breakdowns",id],queryFn:({signal})=>api.get<Breakdown>(`/breakdowns/${id}`,signal)});const corrective=useQuery({queryKey:["breakdowns",id,"corrective"],queryFn:({signal})=>api.get<CorrectiveExecution>(`/breakdowns/${id}/corrective-action`,signal)});const assignments=useQuery({queryKey:["breakdowns",id,"assignments"],queryFn:({signal})=>api.get<BreakdownAssignment[]>(`/breakdowns/${id}/assignments`,signal)});const history=useQuery({queryKey:["breakdowns",id,"history"],queryFn:({signal})=>api.get<TimelineEvent[]>(`/breakdowns/${id}/history`,signal)});const submissions=useQuery({queryKey:["breakdowns",id,"submissions"],queryFn:({signal})=>api.get<CorrectiveSubmission[]>(`/breakdowns/${id}/submissions`,signal)});
 const latestPending=submissions.data?.find((item)=>!item.review);
 const refresh=()=>{client.invalidateQueries({queryKey:["breakdowns",id]});client.invalidateQueries({queryKey:["breakdowns"]})};
 const assign=useMutation({mutationFn:()=>api.post(`/breakdowns/${id}/assign`,{technicianId,supervisorId:supervisorId||null,reason:reason||null}),onSuccess:()=>{showToast("Breakdown assigned");setAssignOpen(false);refresh()}});const returnService=useMutation({mutationFn:()=>api.post(`/breakdowns/${id}/return-to-service`,{remarks:returnRemarks||null}),onSuccess:()=>{showToast("Machine returned to service");setReturnOpen(false);refresh()}});const reviewMutation=useMutation({mutationFn:()=>api.post(`/breakdowns/${id}/${review}`,{submissionId:latestPending?.id,remarks:reviewRemarks||null}),onSuccess:()=>{showToast(review==="approve"?"Corrective work approved":"Corrective work rejected");setReview(undefined);refresh()}});
 if(detail.isPending)return <LoadingSkeleton rows={8}/>;if(detail.error||!detail.data)return <ErrorState error={detail.error}/>;const item=detail.data;const canManage=hasRole("SUPERVISOR","MANAGER","ADMIN");const canReview=hasRole("SUPERVISOR")&&item.status==="AWAITING_APPROVAL"&&latestPending;
 return <div className="page-stack"><PageHeader eyebrow="Breakdown record" title={item.breakdownNumber} description={`${item.machineCode} · ${item.machineName}`} actions={<><Link className="button button-secondary button-md" href="/breakdowns"><ArrowLeft size={16}/> Breakdowns</Link>{canManage&&!["CLOSED","CANCELLED"].includes(item.status)&&<Button variant="secondary" onClick={()=>{setTechnicianId(item.assignedTechnicianId??"");setSupervisorId(item.supervisorId);setAssignOpen(true)}}><UserRoundCog size={16}/> Assign</Button>}{canManage&&item.status==="CLOSED"&&!item.returnedToServiceAt&&<Button onClick={()=>setReturnOpen(true)}><RotateCcw size={16}/> Return to service</Button>}{canReview&&<><Button variant="secondary" onClick={()=>setReview("reject")}><XCircle size={16}/> Reject</Button><Button onClick={()=>setReview("approve")}><CheckCircle2 size={16}/> Approve</Button></>}</>}/><div className="record-status"><StatusBadge value={item.severity}/><StatusBadge value={item.status}/><StatusBadge value={item.machineStopped?"Machine stopped":"Machine running"}/><StatusBadge value={item.downtimeOngoing?"Downtime ongoing":formatMinutes(item.downtimeMinutes)}/></div><Tabs active={tab} onChange={setTab} tabs={[{id:"breakdown",label:"Breakdown"},{id:"corrective",label:"Corrective work"},{id:"evidence",label:"Evidence & parts"},{id:"submissions",label:"Submissions"},{id:"history",label:"History"}]}/>
 {tab==="breakdown"&&<div className="detail-grid"><Card><SectionHeader title="Incident"/><dl className="definition-list"><div><dt>Reported by</dt><dd>{item.reporterName}</dd></div><div><dt>Reported at</dt><dd>{formatDateTime(item.reportedAt)}</dd></div><div><dt>Severity</dt><dd>{item.severity}</dd></div><div><dt>Machine stopped</dt><dd>{item.machineStopped?"Yes":"No"}</dd></div><div><dt>Description</dt><dd>{item.description}</dd></div><div><dt>Initial observation</dt><dd>{item.initialObservation||"—"}</dd></div></dl></Card><Card><SectionHeader title="Response & downtime"/><dl className="definition-list"><div><dt>Technician</dt><dd>{item.technicianName||"Unassigned"}</dd></div><div><dt>Supervisor</dt><dd>{item.supervisorName}</dd></div><div><dt>Started</dt><dd>{formatDateTime(item.startedAt)}</dd></div><div><dt>Completed</dt><dd>{formatDateTime(item.completedAt)}</dd></div><div><dt>Closed</dt><dd>{formatDateTime(item.closedAt)}</dd></div><div><dt>Returned to service</dt><dd>{formatDateTime(item.returnedToServiceAt)}</dd></div><div><dt>Downtime</dt><dd>{formatMinutes(item.downtimeMinutes)}{item.downtimeOngoing?" and counting":""}</dd></div></dl></Card></div>}
 {tab==="corrective"&&<AsyncData query={corrective}>{(data)=><div className="detail-grid"><Card><SectionHeader title="Corrective analysis"/><dl className="definition-list"><div><dt>Root cause</dt><dd>{data.rootCause||"Not documented"}</dd></div><div><dt>Corrective action</dt><dd>{data.correctiveAction||"Not documented"}</dd></div><div><dt>Comments</dt><dd>{data.comments||"—"}</dd></div></dl></Card><Card><SectionHeader title="Execution"/><dl className="definition-list"><div><dt>Technician</dt><dd>{data.technicianName||"Unassigned"}</dd></div><div><dt>Started</dt><dd>{formatDateTime(data.startedAt)}</dd></div><div><dt>Completed</dt><dd>{formatDateTime(data.completedAt)}</dd></div><div><dt>Duration</dt><dd>{formatMinutes(data.durationMinutes)}</dd></div><div><dt>Complete</dt><dd>{data.isComplete?"Yes":"No"}</dd></div></dl></Card></div>}</AsyncData>}
 {tab==="evidence"&&<AsyncData query={corrective}>{(data)=><><Card><SectionHeader title="Evidence"/>{data.attachments.length?<div className="document-list">{data.attachments.map((file)=><DocumentRow file={file} key={file.id} onError={(message)=>showToast(message,"error")}/>)}</div>:<EmptyState title="No evidence" description="Corrective evidence will appear here."/>}</Card><Card><SectionHeader title="Parts replaced"/>{data.parts.length?<div className="record-list">{data.parts.map((part,index)=><pre key={String(part.id??index)}>{Object.entries(part).filter(([key])=>!key.toLowerCase().includes("id")).map(([key,value])=>`${key}: ${String(value??"—")}`).join("\n")}</pre>)}</div>:<EmptyState title="No parts recorded" description="Parts used during corrective work will appear here."/>}</Card></>}</AsyncData>}
 {tab==="submissions"&&<AsyncData query={submissions}>{(data)=>data.length?<div className="submission-list">{data.map((entry)=><Card key={entry.id}><div><strong>Submission v{entry.versionNumber}</strong><StatusBadge value={entry.review?.decision??"Awaiting review"}/></div><dl className="definition-list"><div><dt>Technician</dt><dd>{entry.technicianName}</dd></div><div><dt>Submitted</dt><dd>{formatDateTime(entry.submittedAt)}</dd></div><div><dt>Duration</dt><dd>{formatMinutes(entry.durationMinutes)}</dd></div><div><dt>Reviewer</dt><dd>{entry.review?.supervisorName||"Pending"}</dd></div><div><dt>Remarks</dt><dd>{entry.review?.remarks||"—"}</dd></div></dl></Card>)}</div>:<EmptyState title="No submissions" description="Corrective submissions will appear here."/>}</AsyncData>}
 {tab==="history"&&<div className="detail-grid"><Card><SectionHeader title="Breakdown history"/>{history.isPending?<LoadingSkeleton/>:history.error?<ErrorState error={history.error}/>:<div className="timeline">{history.data?.map((entry)=><article key={entry.id}><i/><div><strong>{entry.action.replaceAll("_"," ")}</strong><p>{entry.actorName||"System"}</p><span>{formatDateTime(entry.occurredAt)}</span>{entry.details&&<small>{entry.details}</small>}</div></article>)}</div>}</Card><Card><SectionHeader title="Assignment history"/>{assignments.isPending?<LoadingSkeleton/>:assignments.error?<ErrorState error={assignments.error}/>:<div className="timeline">{assignments.data?.map((entry)=><article key={entry.id}><i/><div><strong>{entry.technicianName}</strong><p>Supervisor: {entry.supervisorName}</p><span>{formatDateTime(entry.assignedAt)}</span>{entry.reason&&<small>{entry.reason}</small>}</div></article>)}</div>}</Card></div>}
 <Modal open={assignOpen} title="Assign breakdown" onClose={()=>setAssignOpen(false)} footer={<><Button variant="secondary" onClick={()=>setAssignOpen(false)}>Cancel</Button><Button loading={assign.isPending} disabled={!technicianId} onClick={()=>assign.mutate()}>Save assignment</Button></>}><div className="form-stack compact"><Field label="Technician" required><Select value={technicianId} onChange={(event)=>setTechnicianId(event.target.value)}><option value="">Select technician</option>{refs.technicians.data?.map((entry)=><option key={entry.id} value={entry.id}>{entry.employeeId} · {entry.firstName} {entry.lastName}</option>)}</Select></Field><Field label="Supervisor"><Select value={supervisorId} onChange={(event)=>setSupervisorId(event.target.value)}><option value="">Keep current</option>{refs.supervisors.data?.map((entry)=><option key={entry.id} value={entry.id}>{entry.employeeId} · {entry.firstName} {entry.lastName}</option>)}</Select></Field><Field label="Reason"><Input value={reason} onChange={(event)=>setReason(event.target.value)}/></Field>{assign.error&&<p className="field-error">{errorMessage(assign.error)}</p>}</div></Modal>
 <Modal open={returnOpen} title="Return machine to service" onClose={()=>setReturnOpen(false)} footer={<><Button variant="secondary" onClick={()=>setReturnOpen(false)}>Cancel</Button><Button loading={returnService.isPending} onClick={()=>returnService.mutate()}>Confirm return</Button></>}><p>Confirm that corrective work is closed and this machine can safely return to operational status.</p><Field label="Remarks"><Textarea rows={3} value={returnRemarks} onChange={(event)=>setReturnRemarks(event.target.value)}/></Field>{returnService.error&&<p className="field-error">{errorMessage(returnService.error)}</p>}</Modal>
 <Modal open={Boolean(review)} title={review==="approve"?"Approve corrective work":"Reject corrective work"} onClose={()=>setReview(undefined)} footer={<><Button variant="secondary" onClick={()=>setReview(undefined)}>Cancel</Button><Button variant={review==="reject"?"danger":"primary"} loading={reviewMutation.isPending} onClick={()=>reviewMutation.mutate()}>{review==="approve"?"Approve":"Reject"}</Button></>}><Field label="Remarks"><Textarea rows={4} value={reviewRemarks} onChange={(event)=>setReviewRemarks(event.target.value)}/></Field>{reviewMutation.error&&<p className="field-error">{errorMessage(reviewMutation.error)}</p>}</Modal>
 </div>
}
function AsyncData<T>({query,children}:{query:{isPending:boolean;error:unknown;data?:T};children:(data:T)=>React.ReactNode}){if(query.isPending)return <LoadingSkeleton rows={6}/>;if(query.error||query.data===undefined)return <ErrorState error={query.error}/>;return <>{children(query.data)}</>}
function DocumentRow({file,onError}:{file:FileAttachment;onError:(message:string)=>void}){return <div><div><span><strong>{file.originalFilename}</strong><small>{file.mimeType} · {Math.ceil(file.fileSize/1024)} KB</small></span></div><FileAction onClick={()=>api.download(`/files/${file.fileId}`,file.originalFilename).catch((error)=>onError(errorMessage(error)))}/></div>}
