"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FilePlus2, History, RefreshCw } from "lucide-react";
import { useState } from "react";
import { Button, DateControl, Drawer, EmptyState, ErrorState, Field, FileAction, FilterBar, Input, KpiCard, LoadingSkeleton, Modal, PageHeader, Pagination, Search, Select, StatusBadge, Table, Textarea, type TableColumn } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { useAuth } from "@/features/auth/auth-provider";
import { api, errorMessage, queryString } from "@/lib/api-client";
import { formatDate, formatDateTime } from "@/lib/format";
import type { CalibrationCertificate, CalibrationSummary, Machine, PagedResult } from "@/types/api";

interface Renewal { id:string;machineId:string;previousCertificateId?:string|null;status:string;startedAt:string;startedByUserId:string;completedAt?:string|null;completedCertificateId?:string|null;notes?:string|null }

export function CalibrationView(){
 const {hasRole}=useAuth();const canManage=hasRole("MANAGER","ADMIN");const client=useQueryClient();const {showToast}=useToast();const [page,setPage]=useState(1);const [filters,setFilters]=useState({search:"",machineId:"",provider:"",result:"",validityStatus:"",renewalStatus:"",expiryFrom:"",expiryTo:"",expiredOnly:""});const [addOpen,setAddOpen]=useState(false);const [form,setForm]=useState({machineId:"",certificateNumber:"",calibrationProvider:"",calibrationDate:"",expiryDate:"",result:"PASS",remarks:"",recordForNonRequiredMachine:false});const [file,setFile]=useState<File>();const [renewal,setRenewal]=useState<CalibrationCertificate>();const [renewalAction,setRenewalAction]=useState<"start"|"complete"|"cancel">("start");const [renewalNotes,setRenewalNotes]=useState("");const [certificateId,setCertificateId]=useState("");const [historyMachine,setHistoryMachine]=useState<CalibrationCertificate>();
 const summary=useQuery({queryKey:["calibrations","summary"],queryFn:({signal})=>api.get<CalibrationSummary>("/calibrations/summary",signal)});const machines=useQuery({queryKey:["machines","calibration-options"],queryFn:({signal})=>api.get<PagedResult<Machine>>("/machines?Page=1&PageSize=100&IsActive=true",signal)});const params=queryString({Search:filters.search,Page:page,PageSize:20,MachineId:filters.machineId,Provider:filters.provider,Result:filters.result,ValidityStatus:filters.validityStatus,RenewalStatus:filters.renewalStatus,ExpiryFrom:filters.expiryFrom,ExpiryTo:filters.expiryTo,ExpiredOnly:filters.expiredOnly});const certificates=useQuery({queryKey:["calibrations",filters,page],queryFn:({signal})=>api.get<PagedResult<CalibrationCertificate>>(`/calibrations${params}`,signal),placeholderData:(previous)=>previous});const history=useQuery({queryKey:["calibration-renewals",historyMachine?.machineId],queryFn:({signal})=>api.get<Renewal[]>(`/machines/${historyMachine?.machineId}/calibration-renewals`,signal),enabled:Boolean(historyMachine)});
 const create=useMutation({mutationFn:()=>{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,String(value)));if(file)body.append("certificate",file);return api.post<CalibrationCertificate>("/calibrations",body)},onSuccess:()=>{showToast("Calibration certificate added");setAddOpen(false);client.invalidateQueries({queryKey:["calibrations"]})}});
 const renewalMutation=useMutation({mutationFn:()=>api.post(`/machines/${renewal?.machineId}/calibration-renewals/${renewalAction}`,renewalAction==="complete"?{certificateId,notes:renewalNotes||null}:{notes:renewalNotes||null}),onSuccess:()=>{showToast(`Renewal ${renewalAction === "start" ? "started" : renewalAction === "complete" ? "completed" : "cancelled"}`);setRenewal(undefined);client.invalidateQueries({queryKey:["calibrations"]});client.invalidateQueries({queryKey:["calibration-renewals"]})}});
 const set=(name:string,value:string)=>{setFilters((current)=>({...current,[name]:value}));setPage(1)};
 const openRenewal=(row:CalibrationCertificate,action:"start"|"complete"|"cancel")=>{setRenewal(row);setRenewalAction(action);setRenewalNotes("");setCertificateId(row.id)};
 const columns:TableColumn<CalibrationCertificate>[]=[{key:"machine",header:"Machine",cell:(row)=><div className="primary-cell"><strong>{row.machineCode}</strong><span>{row.machineName}</span></div>},{key:"certificate",header:"Certificate",cell:(row)=><div className="primary-cell"><strong>{row.certificateNumber}</strong><span>{row.calibrationProvider}</span></div>},{key:"dates",header:"Calibration / expiry",cell:(row)=><div className="primary-cell"><span>{formatDate(row.calibrationDate)}</span><small>{formatDate(row.expiryDate)}</small></div>},{key:"remaining",header:"Days remaining",cell:(row)=>row.daysRemaining??"—"},{key:"result",header:"Result",cell:(row)=><StatusBadge value={row.result}/>},{key:"status",header:"Validity",cell:(row)=><StatusBadge value={row.validityStatus}/>},{key:"renewal",header:"Renewal",cell:(row)=><StatusBadge value={row.renewalStatus}/>},{key:"actions",header:"Actions",cell:(row)=><div className="table-actions">{row.certificateFileId&&<FileAction label="Certificate" onClick={()=>api.download(`/files/${row.certificateFileId}`,`${row.certificateNumber}.pdf`).catch((error)=>showToast(errorMessage(error),"error"))}/>}<button className="icon-button" aria-label="Renewal history" onClick={()=>setHistoryMachine(row)}><History size={16}/></button>{canManage&&(row.renewalStatus==="IN_PROGRESS"?<><Button variant="ghost" size="sm" onClick={()=>openRenewal(row,"complete")}>Complete</Button><Button variant="ghost" size="sm" onClick={()=>openRenewal(row,"cancel")}>Cancel</Button></>:<Button variant="ghost" size="sm" onClick={()=>openRenewal(row,"start")}><RefreshCw size={14}/> Start</Button>)}</div>}];
 return <div className="page-stack"><PageHeader eyebrow="Compliance" title="Calibration" description="Monitor certificate validity, renewal windows, and calibration evidence." actions={canManage&&<Button onClick={()=>setAddOpen(true)}><FilePlus2 size={16}/> Add certificate</Button>}/>{summary.isPending?<LoadingSkeleton rows={2}/>:summary.error?<ErrorState error={summary.error}/>:summary.data&&<section className="kpi-grid seven"><KpiCard label="Required" value={summary.data.totalCalibrationRequiredMachines}/><KpiCard label="Valid" value={summary.data.valid}/><KpiCard label="Expiring 60" value={summary.data.expiringWithin60Days} tone="blue"/><KpiCard label="Expiring 30" value={summary.data.expiringWithin30Days} tone="gold"/><KpiCard label="Expiring 7" value={summary.data.expiringWithin7Days} tone="terracotta"/><KpiCard label="Expired" value={summary.data.expired} tone="maroon"/><KpiCard label="Renewal in progress" value={summary.data.renewalInProgress} tone="gold"/></section>}<FilterBar onClear={()=>setFilters({search:"",machineId:"",provider:"",result:"",validityStatus:"",renewalStatus:"",expiryFrom:"",expiryTo:"",expiredOnly:""})}><Search value={filters.search} onChange={(event)=>set("search",event.target.value)} placeholder="Machine, certificate or provider…"/><Select aria-label="Machine" value={filters.machineId} onChange={(event)=>set("machineId",event.target.value)}><option value="">All machines</option>{machines.data?.items.map((item)=><option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select><Select aria-label="Validity" value={filters.validityStatus} onChange={(event)=>set("validityStatus",event.target.value)}><option value="">All validity states</option>{["NOT_REQUIRED","VALID","EXPIRING_SOON","EXPIRED"].map((value)=><option key={value}>{value}</option>)}</Select><Select aria-label="Result" value={filters.result} onChange={(event)=>set("result",event.target.value)}><option value="">All results</option><option>PASS</option><option>FAIL</option><option>CONDITIONAL</option></Select><Select aria-label="Renewal" value={filters.renewalStatus} onChange={(event)=>set("renewalStatus",event.target.value)}><option value="">All renewal states</option>{["NOT_STARTED","IN_PROGRESS","COMPLETED","CANCELLED"].map((value)=><option key={value}>{value}</option>)}</Select><DateControl aria-label="Expiry from" value={filters.expiryFrom} onChange={(event)=>set("expiryFrom",event.target.value)}/><DateControl aria-label="Expiry to" value={filters.expiryTo} onChange={(event)=>set("expiryTo",event.target.value)}/></FilterBar>{certificates.isPending?<LoadingSkeleton rows={8}/>:certificates.error?<ErrorState error={certificates.error} onRetry={()=>certificates.refetch()}/>:<><Table columns={columns} items={certificates.data?.items??[]} rowKey={(row)=>row.id}/><Pagination page={certificates.data?.page??page} totalPages={certificates.data?.totalPages??1} totalCount={certificates.data?.totalCount} onPageChange={setPage}/></>}
 <Modal open={addOpen} title="Add calibration certificate" onClose={()=>setAddOpen(false)} size="lg" footer={<><Button variant="secondary" onClick={()=>setAddOpen(false)}>Cancel</Button><Button loading={create.isPending} disabled={!form.machineId||!form.certificateNumber||!form.calibrationProvider||!form.calibrationDate||!form.expiryDate} onClick={()=>create.mutate()}>Add certificate</Button></>}><div className="form-grid"><Field label="Machine" required><Select value={form.machineId} onChange={(event)=>setForm({...form,machineId:event.target.value})}><option value="">Select machine</option>{machines.data?.items.map((item)=><option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select></Field><Field label="Certificate number" required><Input value={form.certificateNumber} onChange={(event)=>setForm({...form,certificateNumber:event.target.value})}/></Field><Field label="Provider" required><Input value={form.calibrationProvider} onChange={(event)=>setForm({...form,calibrationProvider:event.target.value})}/></Field><Field label="Calibration date" required><Input type="date" value={form.calibrationDate} onChange={(event)=>setForm({...form,calibrationDate:event.target.value})}/></Field><Field label="Expiry date" required><Input type="date" value={form.expiryDate} onChange={(event)=>setForm({...form,expiryDate:event.target.value})}/></Field><Field label="Result"><Select value={form.result} onChange={(event)=>setForm({...form,result:event.target.value})}><option>PASS</option><option>FAIL</option><option>CONDITIONAL</option></Select></Field><Field className="field-span" label="Remarks"><Textarea rows={3} value={form.remarks} onChange={(event)=>setForm({...form,remarks:event.target.value})}/></Field><Field className="field-span" label="Certificate file" hint="PDF or supported evidence file"><Input type="file" onChange={(event)=>setFile(event.target.files?.[0])}/></Field></div>{create.error&&<p className="field-error">{errorMessage(create.error)}</p>}</Modal>
 <Modal open={Boolean(renewal)} title={`${renewalAction[0].toUpperCase()+renewalAction.slice(1)} calibration renewal`} onClose={()=>setRenewal(undefined)} footer={<><Button variant="secondary" onClick={()=>setRenewal(undefined)}>Cancel</Button><Button loading={renewalMutation.isPending} disabled={renewalAction==="complete"&&!certificateId} onClick={()=>renewalMutation.mutate()}>Confirm</Button></>}><p>{renewal?.machineCode} · {renewal?.machineName}</p>{renewalAction==="complete"&&<Field label="Completion certificate"><Select value={certificateId} onChange={(event)=>setCertificateId(event.target.value)}>{certificates.data?.items.filter((item)=>item.machineId===renewal?.machineId).map((item)=><option key={item.id} value={item.id}>{item.certificateNumber} · {formatDate(item.expiryDate)}</option>)}</Select></Field>}<Field label="Notes"><Textarea rows={3} value={renewalNotes} onChange={(event)=>setRenewalNotes(event.target.value)}/></Field>{renewalMutation.error&&<p className="field-error">{errorMessage(renewalMutation.error)}</p>}</Modal>
 <Drawer open={Boolean(historyMachine)} title={`${historyMachine?.machineCode??"Machine"} renewal history`} onClose={()=>setHistoryMachine(undefined)}>{history.isPending?<LoadingSkeleton/>:history.error?<ErrorState error={history.error}/>:!history.data?.length?<EmptyState title="No renewal history" description="Renewal activity will appear here."/>:<div className="timeline">{history.data.map((item)=><article key={item.id}><i/><div><strong>{item.status.replaceAll("_"," ")}</strong><span>Started {formatDateTime(item.startedAt)}</span>{item.completedAt&&<span>Completed {formatDateTime(item.completedAt)}</span>}{item.notes&&<small>{item.notes}</small>}</div></article>)}</div>}</Drawer>
 </div>
}
