"use client";

import { AlertTriangle, CalendarDays, Download, FileSearch, Inbox, Search as SearchIcon, X } from "lucide-react";
import Link from "next/link";
import { forwardRef, useEffect, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { errorMessage } from "@/lib/api-client";

export function cx(...values: Array<string | false | null | undefined>) { return values.filter(Boolean).join(" "); }

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; size?: "sm" | "md"; loading?: boolean };
export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button({ variant = "primary", size = "md", loading, className, children, disabled, ...props }, ref) {
  return <button ref={ref} className={cx("button", `button-${variant}`, `button-${size}`, className)} disabled={disabled || loading} {...props}>{loading && <span className="spinner" aria-hidden="true" />}{children}</button>;
});
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function Input({ className, ...props }, ref) { return <input ref={ref} className={cx("input", className)} {...props} />; });
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(function Select({ className, children, ...props }, ref) { return <select ref={ref} className={cx("input select", className)} {...props}>{children}</select>; });
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({ className, ...props }, ref) { return <textarea ref={ref} className={cx("input textarea", className)} {...props} />; });

export function Field({ label, error, hint, required, children, className }: { label: string; error?: string; hint?: string; required?: boolean; children: ReactNode; className?: string }) { return <label className={cx("field", className)}><span className="field-label">{label}{required && <em aria-hidden="true"> *</em>}</span>{children}{error ? <span className="field-error">{error}</span> : hint ? <span className="field-hint">{hint}</span> : null}</label>; }
export function Checkbox({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="checkbox"><input type="checkbox" {...props} /><span>{label}</span></label>; }
export function Search({ value, onChange, placeholder = "Search…", ...props }: InputHTMLAttributes<HTMLInputElement>) { return <div className="search-control"><SearchIcon size={17} /><Input type="search" value={value} onChange={onChange} placeholder={placeholder} {...props} /></div>; }
export function DateControl(props: InputHTMLAttributes<HTMLInputElement>) { return <div className="date-control"><CalendarDays size={16} /><Input type="date" {...props} /></div>; }

export function Card({ className, children, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cx("card", className)} {...props}>{children}</div>; }
export function KpiCard({ label, value, hint, tone = "green", icon }: { label: string; value: ReactNode; hint?: string; tone?: "green" | "gold" | "maroon" | "terracotta" | "blue"; icon?: ReactNode }) { return <Card className={cx("kpi-card", `kpi-${tone}`)}><div className="kpi-top"><span>{label}</span>{icon}</div><strong>{value}</strong>{hint && <small>{hint}</small>}</Card>; }
export function StatusBadge({ value }: { value?: string | boolean | null }) { const label = value === true ? "Active" : value === false ? "Inactive" : value || "Unknown"; const normalized = String(label).replaceAll("_", " ").replace(/([a-z])([A-Z])/g, "$1 $2"); const lower = normalized.toLowerCase(); const tone = /approved|operational|valid|active|completed|pass|closed/.test(lower) ? "success" : /overdue|expired|critical|breakdown|rejected|fail|out of service/.test(lower) ? "danger" : /await|due|progress|soon|assigned|generated|conditional/.test(lower) ? "warning" : "neutral"; return <span className={cx("status-badge", `status-${tone}`)}>{normalized}</span>; }

export interface TableColumn<T> { key: string; header: string; cell: (item: T) => ReactNode; className?: string }
export function Table<T>({ columns, items, rowKey, emptyMessage = "No records match these filters." }: { columns: TableColumn<T>[]; items: T[]; rowKey: (item: T) => string; emptyMessage?: string }) {
  if (!items.length) return <EmptyState title="No records found" description={emptyMessage} />;
  return <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.key} className={column.className}>{column.header}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={rowKey(item)}>{columns.map((column) => <td key={column.key} className={column.className}>{column.cell(item)}</td>)}</tr>)}</tbody></table></div>;
}
export function Pagination({ page, totalPages, totalCount, onPageChange }: { page: number; totalPages: number; totalCount?: number; onPageChange: (page: number) => void }) { if (totalPages <= 1) return totalCount !== undefined ? <p className="pagination-summary">{totalCount} record{totalCount === 1 ? "" : "s"}</p> : null; return <div className="pagination"><span>Page {page} of {totalPages}{totalCount !== undefined && ` · ${totalCount} records`}</span><div><Button variant="secondary" size="sm" disabled={page <= 1} onClick={() => onPageChange(page - 1)}>Previous</Button><Button variant="secondary" size="sm" disabled={page >= totalPages} onClick={() => onPageChange(page + 1)}>Next</Button></div></div>; }
export function FilterBar({ children, onClear }: { children: ReactNode; onClear?: () => void }) { return <Card className="filter-bar"><div className="filter-fields">{children}</div>{onClear && <Button type="button" variant="ghost" size="sm" onClick={onClear}>Clear filters</Button>}</Card>; }
export function Tabs({ tabs, active, onChange }: { tabs: Array<{ id: string; label: string }>; active: string; onChange: (id: string) => void }) { return <div className="tabs" role="tablist">{tabs.map((tab) => <button type="button" role="tab" aria-selected={active === tab.id} className={active === tab.id ? "active" : ""} key={tab.id} onClick={() => onChange(tab.id)}>{tab.label}</button>)}</div>; }

export function LoadingSkeleton({ rows = 5 }: { rows?: number }) { return <div className="skeleton-stack" aria-label="Loading" role="status">{Array.from({ length: rows }, (_, index) => <div className="skeleton" key={index} />)}</div>; }
export function EmptyState({ title, description, action, icon }: { title: string; description: string; action?: ReactNode; icon?: ReactNode }) { return <div className="empty-state">{icon ?? <Inbox size={30} />}<h3>{title}</h3><p>{description}</p>{action}</div>; }
export function ErrorState({ error, onRetry }: { error: unknown; onRetry?: () => void }) { return <div className="error-state" role="alert"><AlertTriangle size={24} /><div><h3>Unable to load this view</h3><p>{errorMessage(error)}</p>{onRetry && <Button variant="secondary" size="sm" onClick={onRetry}>Try again</Button>}</div></div>; }
export function PermissionState({ description = "Your current role does not allow this action." }: { description?: string }) { return <EmptyState icon={<FileSearch size={30} />} title="Permission required" description={description} />; }

export function Modal({ open, title, onClose, children, footer, size = "md" }: { open: boolean; title: string; onClose: () => void; children: ReactNode; footer?: ReactNode; size?: "sm" | "md" | "lg" }) { useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open, onClose]); if (!open) return null; return <div className="overlay" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className={cx("modal", `modal-${size}`)} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button aria-label="Close" onClick={onClose}><X size={20} /></button></header><div className="modal-body">{children}</div>{footer && <footer>{footer}</footer>}</section></div>; }
export function Drawer({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { if (!open) return null; return <div className="overlay drawer-overlay" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="drawer" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button aria-label="Close" onClick={onClose}><X size={20} /></button></header><div className="drawer-body">{children}</div></aside></div>; }
export function ConfirmDialog({ open, title, description, confirmLabel = "Confirm", danger, loading, onConfirm, onClose }: { open: boolean; title: string; description: string; confirmLabel?: string; danger?: boolean; loading?: boolean; onConfirm: () => void; onClose: () => void }) { return <Modal open={open} title={title} onClose={onClose} size="sm" footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant={danger ? "danger" : "primary"} loading={loading} onClick={onConfirm}>{confirmLabel}</Button></>}><p>{description}</p></Modal>; }
export function FileAction({ label = "Download", onClick, href, loading }: { label?: string; onClick?: () => void; href?: string; loading?: boolean }) { return href ? <Link className="button button-secondary button-sm" href={href}><Download size={15} />{label}</Link> : <Button variant="secondary" size="sm" onClick={onClick} loading={loading}><Download size={15} />{label}</Button>; }
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <div className="page-header"><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="page-actions">{actions}</div>}</div>; }
export function SectionHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="section-header"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>; }
