"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, History, Pencil, Plus, UserRoundCog, Wrench } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { Button, Drawer, ErrorState, Field, FilterBar, LoadingSkeleton, Modal, PageHeader, Pagination, Search, Select, StatusBadge, Table, type TableColumn } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { api, errorMessage, queryString } from "@/lib/api-client";
import { formatDateTime } from "@/lib/format";
import { lookupName, lookupUser, useReferenceData } from "@/lib/reference-data";
import type { AssignmentHistory, Machine, MachineStatus, PagedResult } from "@/types/api";

const statuses: MachineStatus[] = ["Operational", "UnderMaintenance", "Breakdown", "OutOfService", "Standby", "Decommissioned"];

export function MachineList() {
  const searchParams = useSearchParams();
  const refs = useReferenceData(); const client = useQueryClient(); const { showToast } = useToast();
  const [filters, setFilters] = useState({ search: searchParams.get("search") ?? "", categoryId: "", departmentId: "", locationId: "", status: "", criticality: "", calibrationRequired: "", ownerUserId: "", supervisorUserId: "", isActive: "true" });
  const [page, setPage] = useState(1); const [statusMachine, setStatusMachine] = useState<Machine>(); const [nextStatus, setNextStatus] = useState<MachineStatus>("Operational"); const [assignMachine, setAssignMachine] = useState<Machine>(); const [ownerId, setOwnerId] = useState(""); const [supervisorId, setSupervisorId] = useState(""); const [reason, setReason] = useState(""); const [historyMachine, setHistoryMachine] = useState<Machine>();
  const params = queryString({ Search: filters.search, Page: page, PageSize: 20, CategoryId: filters.categoryId, DepartmentId: filters.departmentId, LocationId: filters.locationId, Status: filters.status, Criticality: filters.criticality, CalibrationRequired: filters.calibrationRequired, OwnerUserId: filters.ownerUserId, SupervisorUserId: filters.supervisorUserId, IsActive: filters.isActive });
  const query = useQuery({ queryKey: ["machines", filters, page], queryFn: ({ signal }) => api.get<PagedResult<Machine>>(`/machines${params}`, signal), placeholderData: (previous) => previous });
  const history = useQuery({ queryKey: ["machines", historyMachine?.id, "history"], queryFn: ({ signal }) => api.get<AssignmentHistory[]>(`/machines/${historyMachine?.id}/assignment-history`, signal), enabled: Boolean(historyMachine) });
  const statusMutation = useMutation({ mutationFn: () => api.patch<Machine>(`/machines/${statusMachine?.id}/status`, { status: nextStatus }), onSuccess: () => { showToast("Machine status updated"); setStatusMachine(undefined); client.invalidateQueries({ queryKey: ["machines"] }); } });
  const assignmentMutation = useMutation({ mutationFn: () => api.post<Machine>(`/machines/${assignMachine?.id}/assign-owner`, { machineOwnerUserId: ownerId || null, supervisorUserId: supervisorId || null, reason: reason || null }), onSuccess: () => { showToast("Responsibility updated"); setAssignMachine(undefined); client.invalidateQueries({ queryKey: ["machines"] }); } });
  const updateFilter = (name: string, value: string) => { setFilters((current) => ({ ...current, [name]: value })); setPage(1); };
  const columns: TableColumn<Machine>[] = [
    { key: "machine", header: "Machine", cell: (item) => <div className="primary-cell"><strong>{item.machineCode}</strong><span>{item.name}</span></div> },
    { key: "category", header: "Category", cell: (item) => lookupName(refs.categories.data, item.categoryId) },
    { key: "department", header: "Department / location", cell: (item) => <div className="primary-cell"><span>{lookupName(refs.departments.data, item.departmentId)}</span><small>{lookupName(refs.locations.data, item.locationId)}</small></div> },
    { key: "status", header: "Status", cell: (item) => <StatusBadge value={item.status} /> },
    { key: "calibration", header: "Calibration", cell: (item) => <StatusBadge value={item.currentCalibrationStatus} /> },
    { key: "owner", header: "Owner / supervisor", cell: (item) => <div className="primary-cell"><span>{lookupUser(refs.technicians.data, item.machineOwnerUserId)}</span><small>{lookupUser(refs.supervisors.data, item.supervisorUserId)}</small></div> },
    { key: "actions", header: "Actions", className: "actions-cell", cell: (item) => <div className="table-actions"><Link className="icon-button" aria-label={`View ${item.machineCode}`} href={`/machines/${item.id}`}><Eye size={16} /></Link>{refs.canManageMachines && <><Link className="icon-button" aria-label={`Edit ${item.machineCode}`} href={`/machines/${item.id}/edit`}><Pencil size={16} /></Link><button className="icon-button" aria-label={`Change status for ${item.machineCode}`} onClick={() => { setStatusMachine(item); setNextStatus(item.status); }}><Wrench size={16} /></button><button className="icon-button" aria-label={`Assign ${item.machineCode}`} onClick={() => { setAssignMachine(item); setOwnerId(item.machineOwnerUserId ?? ""); setSupervisorId(item.supervisorUserId ?? ""); setReason(""); }}><UserRoundCog size={16} /></button></>}<button className="icon-button" aria-label={`History for ${item.machineCode}`} onClick={() => setHistoryMachine(item)}><History size={16} /></button></div> },
  ];
  return <div className="page-stack"><PageHeader eyebrow="Asset master" title="Machines" description="Manage equipment, responsibility, location, and compliance status." actions={refs.canManageMachines && <Link className="button button-primary button-md" href="/machines/new"><Plus size={16} /> Add machine</Link>} />
    <FilterBar onClear={() => { setFilters({ search: "", categoryId: "", departmentId: "", locationId: "", status: "", criticality: "", calibrationRequired: "", ownerUserId: "", supervisorUserId: "", isActive: "" }); setPage(1); }}><Search value={filters.search} onChange={(event) => updateFilter("search", event.target.value)} placeholder="Code, name, asset or serial…" /><Select aria-label="Category" value={filters.categoryId} onChange={(event) => updateFilter("categoryId", event.target.value)}><option value="">All categories</option>{refs.categories.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Department" value={filters.departmentId} onChange={(event) => updateFilter("departmentId", event.target.value)}><option value="">All departments</option>{refs.departments.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Location" value={filters.locationId} onChange={(event) => updateFilter("locationId", event.target.value)}><option value="">All locations</option>{refs.locations.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Status" value={filters.status} onChange={(event) => updateFilter("status", event.target.value)}><option value="">All statuses</option>{statuses.map((status) => <option key={status}>{status}</option>)}</Select><Select aria-label="Criticality" value={filters.criticality} onChange={(event) => updateFilter("criticality", event.target.value)}><option value="">All criticalities</option>{["Low", "Medium", "High", "Critical"].map((value) => <option key={value}>{value}</option>)}</Select><Select aria-label="Calibration requirement" value={filters.calibrationRequired} onChange={(event) => updateFilter("calibrationRequired", event.target.value)}><option value="">Any calibration requirement</option><option value="true">Required</option><option value="false">Not required</option></Select><Select aria-label="Active state" value={filters.isActive} onChange={(event) => updateFilter("isActive", event.target.value)}><option value="">All records</option><option value="true">Active</option><option value="false">Inactive</option></Select></FilterBar>
    {query.isPending ? <LoadingSkeleton rows={8} /> : query.error ? <ErrorState error={query.error} onRetry={() => query.refetch()} /> : <><Table columns={columns} items={query.data?.items ?? []} rowKey={(item) => item.id} emptyMessage="Try clearing one or more machine filters." /><Pagination page={query.data?.page ?? page} totalPages={query.data?.totalPages ?? 1} totalCount={query.data?.totalCount} onPageChange={setPage} /></>}
    <Modal open={Boolean(statusMachine)} title={`Change ${statusMachine?.machineCode ?? "machine"} status`} onClose={() => setStatusMachine(undefined)} footer={<><Button variant="secondary" onClick={() => setStatusMachine(undefined)}>Cancel</Button><Button loading={statusMutation.isPending} onClick={() => statusMutation.mutate()}>Update status</Button></>}><Field label="New status"><Select value={nextStatus} onChange={(event) => setNextStatus(event.target.value as MachineStatus)}>{statuses.map((status) => <option key={status}>{status}</option>)}</Select></Field>{statusMutation.error && <p className="field-error">{errorMessage(statusMutation.error)}</p>}</Modal>
    <Modal open={Boolean(assignMachine)} title={`Assign ${assignMachine?.machineCode ?? "machine"}`} onClose={() => setAssignMachine(undefined)} footer={<><Button variant="secondary" onClick={() => setAssignMachine(undefined)}>Cancel</Button><Button loading={assignmentMutation.isPending} onClick={() => assignmentMutation.mutate()}>Save assignment</Button></>}><div className="form-stack compact"><Field label="Owner technician"><Select value={ownerId} onChange={(event) => setOwnerId(event.target.value)}><option value="">Unassigned</option>{refs.technicians.data?.map((item) => <option key={item.id} value={item.id}>{item.employeeId} · {item.firstName} {item.lastName}</option>)}</Select></Field><Field label="Supervisor"><Select value={supervisorId} onChange={(event) => setSupervisorId(event.target.value)}><option value="">Unassigned</option>{refs.supervisors.data?.map((item) => <option key={item.id} value={item.id}>{item.employeeId} · {item.firstName} {item.lastName}</option>)}</Select></Field><Field label="Reason"><input className="input" value={reason} onChange={(event) => setReason(event.target.value)} /></Field>{assignmentMutation.error && <p className="field-error">{errorMessage(assignmentMutation.error)}</p>}</div></Modal>
    <Drawer open={Boolean(historyMachine)} title={`${historyMachine?.machineCode ?? "Machine"} assignment history`} onClose={() => setHistoryMachine(undefined)}>{history.isPending ? <LoadingSkeleton /> : history.error ? <ErrorState error={history.error} /> : !history.data?.length ? <p className="muted">No assignment changes have been recorded.</p> : <div className="timeline">{history.data.map((item) => <article key={item.id}><i /><div><strong>{lookupUser(refs.technicians.data, item.technicianId)}</strong><p>Supervisor: {lookupUser(refs.supervisors.data, item.supervisorId)}</p><span>{formatDateTime(item.effectiveFrom)}{item.effectiveTo ? ` – ${formatDateTime(item.effectiveTo)}` : " – Current"}</span>{item.reason && <small>{item.reason}</small>}</div></article>)}</div>}</Drawer>
  </div>;
}
