"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Pencil, UserRound } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Card, EmptyState, ErrorState, FileAction, LoadingSkeleton, PageHeader, Pagination, SectionHeader, StatusBadge, Table, Tabs, type TableColumn } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { api, errorMessage } from "@/lib/api-client";
import { formatDate, formatDateTime } from "@/lib/format";
import { lookupName, lookupUser, useReferenceData } from "@/lib/reference-data";
import type { AssignmentHistory, Breakdown, CalibrationCertificate, ExternalService, Machine, MachineDocument, PagedResult, WorkOrderSummary } from "@/types/api";

export function MachineDetail({ id }: { id: string }) {
  const [tab, setTab] = useState("overview"); const [page, setPage] = useState(1); const { showToast } = useToast(); const refs = useReferenceData();
  const machine = useQuery({ queryKey: ["machines", id], queryFn: ({ signal }) => api.get<Machine>(`/machines/${id}`, signal) });
  const history = useQuery({ queryKey: ["machines", id, "assignment-history"], queryFn: ({ signal }) => api.get<AssignmentHistory[]>(`/machines/${id}/assignment-history`, signal), enabled: tab === "assignments" });
  const maintenance = useQuery({ queryKey: ["machines", id, "maintenance", page], queryFn: ({ signal }) => api.get<PagedResult<WorkOrderSummary>>(`/machines/${id}/maintenance-history?Page=${page}&PageSize=15`, signal), enabled: tab === "maintenance" });
  const calibration = useQuery({ queryKey: ["machines", id, "calibrations", page], queryFn: ({ signal }) => api.get<PagedResult<CalibrationCertificate>>(`/machines/${id}/calibrations?Page=${page}&PageSize=15`, signal), enabled: tab === "calibration" });
  const breakdowns = useQuery({ queryKey: ["machines", id, "breakdowns", page], queryFn: ({ signal }) => api.get<PagedResult<Breakdown>>(`/machines/${id}/breakdown-history?Page=${page}&PageSize=15`, signal), enabled: tab === "breakdowns" });
  const services = useQuery({ queryKey: ["machines", id, "external-services", page], queryFn: ({ signal }) => api.get<PagedResult<ExternalService>>(`/machines/${id}/external-services?Page=${page}&PageSize=15`, signal), enabled: tab === "services" });
  const documents = useQuery({ queryKey: ["machines", id, "documents", page], queryFn: ({ signal }) => api.get<PagedResult<MachineDocument>>(`/machines/${id}/documents?Page=${page}&PageSize=15&IsActive=true`, signal), enabled: tab === "documents" });
  if (machine.isPending) return <LoadingSkeleton rows={8} />;
  if (machine.error || !machine.data) return <ErrorState error={machine.error} onRetry={() => machine.refetch()} />;
  const item = machine.data;
  return <div className="page-stack"><PageHeader eyebrow="Machine record" title={`${item.machineCode} · ${item.name}`} description={`${lookupName(refs.departments.data, item.departmentId)} · ${lookupName(refs.locations.data, item.locationId)}`} actions={<><Link className="button button-secondary button-md" href="/machines"><ArrowLeft size={16} /> Machines</Link>{refs.canManageMachines && <Link className="button button-primary button-md" href={`/machines/${id}/edit`}><Pencil size={16} /> Edit</Link>}</>} />
    <div className="record-status"><StatusBadge value={item.status} /><StatusBadge value={item.criticality} /><StatusBadge value={item.isActive} />{item.calibrationRequired && <StatusBadge value={item.currentCalibrationStatus} />}</div>
    <Tabs active={tab} onChange={(value) => { setTab(value); setPage(1); }} tabs={[{ id: "overview", label: "Overview" }, { id: "assignments", label: "Assignments" }, { id: "maintenance", label: "Maintenance" }, { id: "calibration", label: "Calibration" }, { id: "breakdowns", label: "Breakdowns" }, { id: "services", label: "External services" }, { id: "documents", label: "Documents" }]} />
    {tab === "overview" && <div className="detail-grid"><Card><SectionHeader title="Identification" /><DefinitionList items={[ ["Machine code", item.machineCode], ["Asset number", item.assetNumber], ["Category", lookupName(refs.categories.data, item.categoryId)], ["Manufacturer", item.manufacturer], ["Model", item.model], ["Serial number", item.serialNumber] ]} /></Card><Card><SectionHeader title="Responsibility" /><DefinitionList items={[ ["Owner technician", lookupUser(refs.technicians.data, item.machineOwnerUserId)], ["Supervisor", lookupUser(refs.supervisors.data, item.supervisorUserId)], ["Department", lookupName(refs.departments.data, item.departmentId)], ["Location", lookupName(refs.locations.data, item.locationId)] ]} /></Card><Card><SectionHeader title="Compliance" /><DefinitionList items={[ ["Calibration", item.calibrationRequired ? item.currentCalibrationStatus : "Not required"], ["Certificate", item.currentCertificateNumber], ["Calibration expiry", formatDate(item.calibrationExpiryDate)], ["Preventive maintenance", item.preventiveMaintenanceRequired ? "Required" : "Not required"], ["Warranty expiry", formatDate(item.warrantyExpiryDate)] ]} /></Card><Card><SectionHeader title="Dates & notes" /><DefinitionList items={[ ["Installed", formatDate(item.installationDate)], ["Commissioned", formatDate(item.commissioningDate)], ["Created", formatDateTime(item.createdAt)], ["Last updated", formatDateTime(item.updatedAt)], ["Notes", item.notes] ]} /></Card></div>}
    {tab === "assignments" && <AsyncPanel query={history}>{(items) => !items.length ? <EmptyState title="No assignment history" description="Owner and supervisor changes will be retained here." /> : <div className="timeline">{items.map((entry) => <article key={entry.id}><i/><div><strong><UserRound size={15}/> {lookupUser(refs.technicians.data, entry.technicianId)}</strong><p>Supervisor: {lookupUser(refs.supervisors.data, entry.supervisorId)}</p><span>{formatDateTime(entry.effectiveFrom)}{entry.effectiveTo ? ` – ${formatDateTime(entry.effectiveTo)}` : " – Current"}</span>{entry.reason && <small>{entry.reason}</small>}</div></article>)}</div>}</AsyncPanel>}
    {tab === "maintenance" && <PagedPanel query={maintenance} page={page} setPage={setPage} columns={maintenanceColumns} rowKey={(row) => row.id} />}
    {tab === "calibration" && <PagedPanel query={calibration} page={page} setPage={setPage} columns={calibrationColumns} rowKey={(row) => row.id} />}
    {tab === "breakdowns" && <PagedPanel query={breakdowns} page={page} setPage={setPage} columns={breakdownColumns} rowKey={(row) => row.id} />}
    {tab === "services" && <PagedPanel query={services} page={page} setPage={setPage} columns={serviceColumns} rowKey={(row) => row.id} />}
    {tab === "documents" && <PagedPanel query={documents} page={page} setPage={setPage} columns={[{ key: "title", header: "Document", cell: (row) => <div className="primary-cell"><strong>{row.title}</strong><span>{row.documentType}</span></div> }, { key: "date", header: "Date / expiry", cell: (row) => <div className="primary-cell"><span>{formatDate(row.documentDate)}</span><small>{formatDate(row.expiryDate)}</small></div> }, { key: "status", header: "Status", cell: (row) => <StatusBadge value={row.expiryStatus} /> }, { key: "action", header: "", cell: (row) => <FileAction onClick={() => api.download(`/files/${row.fileId}`, row.originalFilename).catch((error) => showToast(errorMessage(error), "error"))} /> }]} rowKey={(row) => row.id} />}
  </div>;
}

function DefinitionList({ items }: { items: Array<[string, unknown]> }) { return <dl className="definition-list">{items.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{String(value ?? "—")}</dd></div>)}</dl>; }
function AsyncPanel<T>({ query, children }: { query: { isPending: boolean; error: unknown; data?: T; refetch: () => unknown }; children: (data: T) => React.ReactNode }) { return query.isPending ? <LoadingSkeleton rows={6} /> : query.error || query.data === undefined ? <ErrorState error={query.error} onRetry={() => query.refetch()} /> : <Card>{children(query.data)}</Card>; }
function PagedPanel<T>({ query, page, setPage, columns, rowKey }: { query: { isPending: boolean; error: unknown; data?: PagedResult<T>; refetch: () => unknown }; page: number; setPage: (page: number) => void; columns: TableColumn<T>[]; rowKey: (row: T) => string }) { return query.isPending ? <LoadingSkeleton rows={6} /> : query.error ? <ErrorState error={query.error} onRetry={() => query.refetch()} /> : <Card><Table columns={columns} items={query.data?.items ?? []} rowKey={rowKey} /><Pagination page={query.data?.page ?? page} totalPages={query.data?.totalPages ?? 1} totalCount={query.data?.totalCount} onPageChange={setPage} /></Card>; }
const maintenanceColumns: TableColumn<WorkOrderSummary>[] = [{ key: "wo", header: "Work order", cell: (row) => <Link href={`/work-orders/${row.id}`}>{row.workOrderNumber}</Link> }, { key: "plan", header: "Plan", cell: (row) => row.planName }, { key: "date", header: "Due", cell: (row) => formatDate(row.dueDate) }, { key: "status", header: "Status", cell: (row) => <StatusBadge value={row.lifecycleStatus} /> }];
const calibrationColumns: TableColumn<CalibrationCertificate>[] = [{ key: "certificate", header: "Certificate", cell: (row) => row.certificateNumber }, { key: "provider", header: "Provider", cell: (row) => row.calibrationProvider }, { key: "expiry", header: "Expiry", cell: (row) => formatDate(row.expiryDate) }, { key: "status", header: "Status", cell: (row) => <StatusBadge value={row.validityStatus} /> }];
const breakdownColumns: TableColumn<Breakdown>[] = [{ key: "number", header: "Breakdown", cell: (row) => <Link href={`/breakdowns/${row.id}`}>{row.breakdownNumber}</Link> }, { key: "reported", header: "Reported", cell: (row) => formatDateTime(row.reportedAt) }, { key: "severity", header: "Severity", cell: (row) => <StatusBadge value={row.severity} /> }, { key: "status", header: "Status", cell: (row) => <StatusBadge value={row.status} /> }];
const serviceColumns: TableColumn<ExternalService>[] = [{ key: "number", header: "Service", cell: (row) => <Link href={`/external-services/${row.id}`}>{row.serviceNumber}</Link> }, { key: "company", header: "Company", cell: (row) => row.serviceCompany }, { key: "date", header: "Service date", cell: (row) => formatDate(row.serviceDate) }, { key: "follow", header: "Next / follow-up", cell: (row) => formatDate(row.followUpDate ?? row.nextServiceDate) }];
