"use client";

import { useQuery } from "@tanstack/react-query";
import { addDays, addMonths, addWeeks, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek, subDays, subMonths, subWeeks } from "date-fns";
import { ChevronLeft, ChevronRight } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Button, Card, Drawer, EmptyState, ErrorState, LoadingSkeleton, PageHeader, StatusBadge, Tabs } from "@/components/ui";
import { api, queryString } from "@/lib/api-client";
import { formatDate } from "@/lib/format";
import type { WorkOrderSummary } from "@/types/api";

type View = "month"|"week"|"day";
const iso=(date:Date)=>format(date,"yyyy-MM-dd");

export function CalendarView(){
 const [view,setView]=useState<View>("month");const [cursor,setCursor]=useState(new Date());const [selected,setSelected]=useState<WorkOrderSummary>();
 const range=useMemo(()=>view==="month"?{from:startOfWeek(startOfMonth(cursor),{weekStartsOn:1}),to:endOfWeek(endOfMonth(cursor),{weekStartsOn:1})}:view==="week"?{from:startOfWeek(cursor,{weekStartsOn:1}),to:endOfWeek(cursor,{weekStartsOn:1})}:{from:cursor,to:cursor},[cursor,view]);
 const query=useQuery({queryKey:["calendar",view,iso(range.from),iso(range.to)],queryFn:({signal})=>api.get<WorkOrderSummary[]>(`/work-orders/calendar${queryString({From:iso(range.from),To:iso(range.to)})}`,signal)});
 const days=eachDayOfInterval({start:range.from,end:range.to});const move=(direction:number)=>setCursor((date)=>view==="month"?(direction>0?addMonths(date,1):subMonths(date,1)):view==="week"?(direction>0?addWeeks(date,1):subWeeks(date,1)):(direction>0?addDays(date,1):subDays(date,1)));
 const title=view==="month"?format(cursor,"MMMM yyyy"):view==="week"?`${format(range.from,"d MMM")} – ${format(range.to,"d MMM yyyy")}`:format(cursor,"EEEE, d MMMM yyyy");
 return <div className="page-stack"><PageHeader eyebrow="Maintenance schedule" title="Calendar" description="Review planned work in month, week, or day context."/><Card className="calendar-toolbar"><div><Button variant="ghost" aria-label="Previous period" onClick={()=>move(-1)}><ChevronLeft size={18}/></Button><Button variant="secondary" onClick={()=>setCursor(new Date())}>Today</Button><Button variant="ghost" aria-label="Next period" onClick={()=>move(1)}><ChevronRight size={18}/></Button><strong>{title}</strong></div><Tabs active={view} onChange={(value)=>setView(value as View)} tabs={[{id:"month",label:"Month"},{id:"week",label:"Week"},{id:"day",label:"Day"}]}/></Card>{query.isPending?<LoadingSkeleton rows={7}/>:query.error?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:view==="month"?<MonthGrid days={days} cursor={cursor} events={query.data??[]} onSelect={setSelected}/>:<AgendaGrid days={days} events={query.data??[]} onSelect={setSelected}/>}<Drawer open={Boolean(selected)} title={selected?.workOrderNumber??"Work order"} onClose={()=>setSelected(undefined)}>{selected&&<div className="form-stack compact"><div className="record-status"><StatusBadge value={selected.lifecycleStatus}/><StatusBadge value={selected.overdue?"Overdue":selected.isDueToday?"Due today":"Upcoming"}/><StatusBadge value={selected.priority}/></div><dl className="definition-list"><div><dt>Machine</dt><dd>{selected.machineCode} · {selected.machineName}</dd></div><div><dt>Plan</dt><dd>{selected.planName}</dd></div><div><dt>Technician</dt><dd>{selected.assignedTechnicianName||"Unassigned"}</dd></div><div><dt>Supervisor</dt><dd>{selected.supervisorName}</dd></div><div><dt>Planned</dt><dd>{formatDate(selected.plannedDate)}</dd></div><div><dt>Due</dt><dd>{formatDate(selected.dueDate)}</dd></div></dl><Link className="button button-primary button-md" href={`/work-orders/${selected.id}`}>Open work order</Link></div>}</Drawer></div>;
}

function EventButton({event,onSelect}:{event:WorkOrderSummary;onSelect:(event:WorkOrderSummary)=>void}){const tone=event.overdue?"overdue":event.lifecycleStatus==="APPROVED"?"approved":event.lifecycleStatus==="AWAITING_APPROVAL"?"awaiting":"upcoming";return <button className={`calendar-event event-${tone}`} onClick={()=>onSelect(event)} title={`${event.workOrderNumber} · ${event.machineName}`}><strong>{event.workOrderNumber}</strong><span>{event.machineCode}</span></button>}
function MonthGrid({days,cursor,events,onSelect}:{days:Date[];cursor:Date;events:WorkOrderSummary[];onSelect:(event:WorkOrderSummary)=>void}){return <Card className="month-calendar"><div className="weekday-row">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day)=><strong key={day}>{day}</strong>)}</div><div className="month-grid">{days.map((day)=>{const matches=events.filter((event)=>event.plannedDate===iso(day));return <div key={day.toISOString()} className={`${!isSameMonth(day,cursor)?"outside":""} ${isSameDay(day,new Date())?"today":""}`}><time>{format(day,"d")}</time><div>{matches.slice(0,3).map((event)=><EventButton event={event} onSelect={onSelect} key={event.id}/>)}{matches.length>3&&<small>+{matches.length-3} more</small>}</div></div>})}</div></Card>}
function AgendaGrid({days,events,onSelect}:{days:Date[];events:WorkOrderSummary[];onSelect:(event:WorkOrderSummary)=>void}){return <div className="agenda-grid">{days.map((day)=>{const matches=events.filter((event)=>event.plannedDate===iso(day));return <Card key={day.toISOString()} className="agenda-day"><header><strong>{format(day,"EEE")}</strong><span>{format(day,"d MMM")}</span></header><div>{matches.length?matches.map((event)=><EventButton key={event.id} event={event} onSelect={onSelect}/>):<EmptyState title="No work planned" description="No events on this date."/>}</div></Card>})}</div>}
