"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, Download, UserRoundCog, XCircle } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Button, Card, EmptyState, ErrorState, Field, FileAction, LoadingSkeleton, Modal, PageHeader, SectionHeader, Select, StatusBadge, Tabs, Textarea } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { useAuth } from "@/features/auth/auth-provider";
import { api, errorMessage } from "@/lib/api-client";
import { formatDate, formatDateTime, formatMinutes } from "@/lib/format";
import { useReferenceData } from "@/lib/reference-data";
import type { PagedResult, TimelineEvent, WorkOrderDetail, WorkOrderExecution, WorkOrderSubmissionSummary } from "@/types/api";

interface Escalation { id: string; level: number; triggerType: string; triggeredAt: string; resolvedAt?: string | null; routingReason?: string | null }

export function WorkOrderDetailView({ id }: { id: string }) {
  const { hasRole } = useAuth(); const refs = useReferenceData(); const client = useQueryClient(); const { showToast } = useToast(); const [tab,setTab]=useState("snapshot"); const [review,setReview]=useState<"approve"|"reject">(); const [remarks,setRemarks]=useState(""); const [assignOpen,setAssignOpen]=useState(false); const [technicianId,setTechnicianId]=useState("");
  const detail=useQuery({queryKey:["work-orders",id],queryFn:({signal})=>api.get<WorkOrderDetail>(`/work-orders/${id}`,signal)});
  const execution=useQuery({queryKey:["work-orders",id,"execution"],queryFn:({signal})=>api.get<WorkOrderExecution>(`/work-orders/${id}/execution`,signal)});
  const submissions=useQuery({queryKey:["work-orders",id,"submissions"],queryFn:({signal})=>api.get<WorkOrderSubmissionSummary[]>(`/work-orders/${id}/submissions`,signal)});
  const history=useQuery({queryKey:["work-orders",id,"history"],queryFn:({signal})=>api.get<TimelineEvent[]>(`/work-orders/${id}/history`,signal)});
  const escalations=useQuery({queryKey:["escalations",id],queryFn:({signal})=>api.get<PagedResult<Escalation>>(`/escalations?WorkOrderId=${id}&Page=1&PageSize=50`,signal),enabled:hasRole("SUPERVISOR","MANAGER","ADMIN")});
  const activeSubmission=submissions.data?.find((item)=>!item.review);
  const reviewMutation=useMutation({mutationFn:()=>api.post(`/work-orders/${id}/${review}`,{submissionId:activeSubmission?.id,remarks:remarks||null}),onSuccess:()=>{showToast(review==="approve"?"Work order approved":"Work order returned for correction");setReview(undefined);setRemarks("");client.invalidateQueries({queryKey:["work-orders",id]});}});
  const assignment=useMutation({mutationFn:()=>api.post(`/work-orders/${id}/assignment`,{technicianId}),onSuccess:()=>{showToast("Technician assignment updated");setAssignOpen(false);client.invalidateQueries({queryKey:["work-orders",id]});}});
  if(detail.isPending)return <LoadingSkeleton rows={8}/>;
  if(detail.error||!detail.data)return <ErrorState error={detail.error} onRetry={()=>detail.refetch()}/>;
  const order=detail.data.workOrder; const definition=detail.data.definition; const canAssign=hasRole("MANAGER","ADMIN")&&["PLANNED","ASSIGNED","REJECTED"].includes(order.lifecycleStatus); const canReview=hasRole("SUPERVISOR")&&order.lifecycleStatus==="AWAITING_APPROVAL"&&activeSubmission;
  return <div className="page-stack"><PageHeader eyebrow="Work order" title={order.workOrderNumber} description={`${order.machineCode} · ${order.machineName} · ${order.planName}`} actions={<><Link className="button button-secondary button-md" href="/work-orders"><ArrowLeft size={16}/> Work orders</Link>{canAssign&&<Button onClick={()=>{setTechnicianId(order.assignedTechnicianId??"");setAssignOpen(true);}}><UserRoundCog size={16}/> Assign</Button>}{canReview&&<><Button variant="secondary" onClick={()=>setReview("reject")}><XCircle size={16}/> Reject</Button><Button onClick={()=>setReview("approve")}><CheckCircle2 size={16}/> Approve</Button></>}</>}/><div className="record-status"><StatusBadge value={order.lifecycleStatus}/><StatusBadge value={order.priority}/><StatusBadge value={order.overdue?`${order.daysOverdue} days overdue`:order.isDueToday?"Due today":"On schedule"}/>{order.escalationLevel>0&&<StatusBadge value={`Escalation level ${order.escalationLevel}`}/>}</div>
    <Tabs active={tab} onChange={setTab} tabs={[{id:"snapshot",label:"Snapshot"},{id:"execution",label:"Execution"},{id:"submissions",label:"Submissions"},{id:"evidence",label:"Evidence"},{id:"history",label:"History & escalation"}]}/>
    {tab==="snapshot"&&<><div className="detail-grid"><Card><SectionHeader title="Schedule & assignment"/><dl className="definition-list"><div><dt>Planned date</dt><dd>{formatDate(order.plannedDate)}</dd></div><div><dt>Due date</dt><dd>{formatDate(order.dueDate)}</dd></div><div><dt>Technician</dt><dd>{order.assignedTechnicianName||"Unassigned"}</dd></div><div><dt>Supervisor</dt><dd>{order.supervisorName}</dd></div><div><dt>Lifecycle</dt><dd>{order.lifecycleStatus}</dd></div><div><dt>Escalation</dt><dd>{order.escalationLevel||"None"}</dd></div></dl></Card><Card><SectionHeader title="Immutable plan snapshot" description={`Checklist version ${definition.checklistVersion}`}/><dl className="definition-list"><div><dt>Maintenance type</dt><dd>{definition.maintenanceTypeName}</dd></div><div><dt>Checklist</dt><dd>{definition.checklistName}</dd></div><div><dt>Estimated duration</dt><dd>{definition.estimatedDurationMinutes?`${definition.estimatedDurationMinutes} minutes`:"—"}</dd></div><div><dt>Photo requirement</dt><dd>{definition.photoRequired?`${definition.minimumPhotoCount} minimum`:"Not required"}</dd></div><div><dt>Comment</dt><dd>{definition.commentRequired?"Required":"Optional"}</dd></div></dl></Card></div><Card><SectionHeader title="Instructions"/><p className="preserve-lines">{definition.instructions||"No instructions were included in this work-order snapshot."}</p></Card><Card><SectionHeader title="Checklist"/><div className="checklist-readonly">{definition.items.map((item)=><article key={item.id}><span>{item.sequenceNumber}</span><div><strong>{item.title}</strong><p>{item.description||item.responseType.replaceAll("_"," ")}{item.unit&&` · ${item.unit}`}</p></div><div className="badge-row">{item.isMandatory&&<StatusBadge value="Mandatory"/>}{item.photoRequired&&<StatusBadge value="Photo required"/>}</div></article>)}</div></Card></>}
    {tab==="execution"&&<AsyncData query={execution}>{(data)=><><div className="detail-grid"><Card><SectionHeader title="Execution timing"/><dl className="definition-list"><div><dt>Started</dt><dd>{formatDateTime(data.startedAt)}</dd></div><div><dt>Completed</dt><dd>{formatDateTime(data.completedAt)}</dd></div><div><dt>Submitted</dt><dd>{formatDateTime(data.submittedAt)}</dd></div><div><dt>Approved</dt><dd>{formatDateTime(data.approvedAt)}</dd></div><div><dt>Duration</dt><dd>{formatMinutes(data.durationMinutes)}</dd></div></dl></Card><Card><SectionHeader title="Technician notes"/><dl className="definition-list"><div><dt>Technician</dt><dd>{data.technicianName||"Unassigned"}</dd></div><div><dt>Overall comments</dt><dd>{data.overallComments||"—"}</dd></div><div><dt>Observations</dt><dd>{data.observations||"—"}</dd></div></dl></Card></div><RecordList title="Checklist responses" records={data.checklistResults}/><RecordList title="Parts used" records={data.parts}/><RecordList title="Defects" records={data.defects}/></>}</AsyncData>}
    {tab==="submissions"&&<AsyncData query={submissions}>{(data)=>!data.length?<EmptyState title="No submissions" description="Technician submissions and supervisor decisions will appear here."/>:<div className="submission-list">{data.map((item)=><Card key={item.id}><div><strong>Submission v{item.versionNumber}</strong><StatusBadge value={item.review?.decision??"Awaiting review"}/></div><dl className="definition-list"><div><dt>Technician</dt><dd>{item.technicianName}</dd></div><div><dt>Submitted</dt><dd>{formatDateTime(item.submittedAt)}</dd></div><div><dt>Duration</dt><dd>{formatMinutes(item.durationMinutes)}</dd></div><div><dt>Decision</dt><dd>{item.review?`${item.review.supervisorName} · ${formatDateTime(item.review.decisionAt)}`:"Pending"}</dd></div><div><dt>Remarks</dt><dd>{item.review?.remarks||"—"}</dd></div></dl></Card>)}</div>}</AsyncData>}
    {tab==="evidence"&&<AsyncData query={execution}>{(data)=>!data.attachments.length?<EmptyState title="No evidence files" description="Uploaded completion evidence will appear here."/>:<Card><div className="document-list">{data.attachments.map((file)=><div key={file.id}><div><Download size={18}/><span><strong>{file.originalFilename}</strong><small>{file.mimeType} · {Math.ceil(file.fileSize/1024)} KB</small></span></div><FileAction onClick={()=>api.download(`/files/${file.fileId}`,file.originalFilename).catch((error)=>showToast(errorMessage(error),"error"))}/></div>)}</div></Card>}</AsyncData>}
    {tab==="history"&&<div className="detail-grid"><Card><SectionHeader title="Lifecycle history"/>{history.isPending?<LoadingSkeleton/>:history.error?<ErrorState error={history.error}/>:<div className="timeline">{history.data?.map((item)=><article key={item.id}><i/><div><strong>{item.action.replaceAll("_"," ")}</strong><p>{item.actorName||"System"}</p><span>{formatDateTime(item.occurredAt)}</span>{item.details&&<small>{item.details}</small>}</div></article>)}</div>}</Card><Card><SectionHeader title="Notification & escalation"/>{!hasRole("SUPERVISOR","MANAGER","ADMIN")?<p className="muted">Escalation history is restricted.</p>:escalations.isPending?<LoadingSkeleton/>:escalations.error?<ErrorState error={escalations.error}/>:!escalations.data?.items.length?<EmptyState title="No escalations" description="This work order has not escalated."/>:<div className="timeline">{escalations.data.items.map((item)=><article key={item.id}><i/><div><strong>Level {item.level} · {item.triggerType.replaceAll("_"," ")}</strong><p>{item.routingReason||"Standard routing"}</p><span>{formatDateTime(item.triggeredAt)}</span>{item.resolvedAt&&<small>Resolved {formatDateTime(item.resolvedAt)}</small>}</div></article>)}</div>}</Card></div>}
    <Modal open={Boolean(review)} title={review==="approve"?"Approve work order":"Reject work order"} onClose={()=>setReview(undefined)} footer={<><Button variant="secondary" onClick={()=>setReview(undefined)}>Cancel</Button><Button variant={review==="reject"?"danger":"primary"} loading={reviewMutation.isPending} onClick={()=>reviewMutation.mutate()}>{review==="approve"?"Approve":"Reject"}</Button></>}><Field label="Review remarks" hint={review==="reject"?"Explain what the technician must correct.":"Optional approval note"}><Textarea rows={4} value={remarks} onChange={(event)=>setRemarks(event.target.value)}/></Field>{reviewMutation.error&&<p className="field-error">{errorMessage(reviewMutation.error)}</p>}</Modal>
    <Modal open={assignOpen} title="Assign technician" onClose={()=>setAssignOpen(false)} footer={<><Button variant="secondary" onClick={()=>setAssignOpen(false)}>Cancel</Button><Button loading={assignment.isPending} disabled={!technicianId} onClick={()=>assignment.mutate()}>Save assignment</Button></>}><Field label="Technician"><Select value={technicianId} onChange={(event)=>setTechnicianId(event.target.value)}><option value="">Select technician</option>{refs.technicians.data?.map((item)=><option key={item.id} value={item.id}>{item.employeeId} · {item.firstName} {item.lastName}</option>)}</Select></Field>{assignment.error&&<p className="field-error">{errorMessage(assignment.error)}</p>}</Modal>
  </div>;
}

function AsyncData<T>({query,children}:{query:{isPending:boolean;error:unknown;data?:T;refetch:()=>unknown};children:(data:T)=>React.ReactNode}){if(query.isPending)return <LoadingSkeleton rows={6}/>;if(query.error||query.data===undefined)return <ErrorState error={query.error} onRetry={()=>query.refetch()}/>;return <>{children(query.data)}</>}
function RecordList({title,records}:{title:string;records:Record<string,unknown>[]}){return <Card><SectionHeader title={title}/>{!records.length?<p className="muted">No records.</p>:<div className="record-list">{records.map((record,index)=><pre key={String(record.id??index)}>{Object.entries(record).filter(([key])=>!key.toLowerCase().includes("id")).map(([key,value])=>`${key.replace(/([A-Z])/g," $1")}: ${String(value??"—")}`).join("\n")}</pre>)}</div>}</Card>}
