"use client";

import { useQuery } from "@tanstack/react-query";
import { Eye } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { DateControl, ErrorState, FilterBar, LoadingSkeleton, PageHeader, Pagination, Search, Select, StatusBadge, Table, type TableColumn } from "@/components/ui";
import { api, queryString } from "@/lib/api-client";
import { formatDate } from "@/lib/format";
import { useReferenceData } from "@/lib/reference-data";
import type { Machine, PagedResult, WorkOrderSummary } from "@/types/api";

export function WorkOrderList() {
  const url = useSearchParams(); const refs = useReferenceData();
  const [filters, setFilters] = useState({ search: url.get("search") ?? "", machineId: "", technicianId: "", supervisorId: "", lifecycleStatus: "", priority: "", plannedFrom: "", plannedTo: "", overdue: url.get("overdue") ?? "" }); const [page, setPage] = useState(1);
  const machines = useQuery({ queryKey: ["machines", "work-order-options"], queryFn: ({ signal }) => api.get<PagedResult<Machine>>("/machines?Page=1&PageSize=100&IsActive=true", signal) });
  const params = queryString({ Search: filters.search, Page: page, PageSize: 20, MachineId: filters.machineId, TechnicianId: filters.technicianId, SupervisorId: filters.supervisorId, LifecycleStatus: filters.lifecycleStatus, Priority: filters.priority, PlannedFrom: filters.plannedFrom, PlannedTo: filters.plannedTo, Overdue: filters.overdue });
  const orders = useQuery({ queryKey: ["work-orders", filters, page], queryFn: ({ signal }) => api.get<PagedResult<WorkOrderSummary>>(`/work-orders${params}`, signal), placeholderData: (previous) => previous });
  const set = (name: string, value: string) => { setFilters((current) => ({ ...current, [name]: value })); setPage(1); };
  const columns: TableColumn<WorkOrderSummary>[] = [{ key:"number",header:"Work order",cell:(row)=><div className="primary-cell"><strong>{row.workOrderNumber}</strong><span>{row.planName}</span></div>},{key:"machine",header:"Machine",cell:(row)=><div className="primary-cell"><strong>{row.machineCode}</strong><span>{row.machineName}</span></div>},{key:"assigned",header:"Technician / supervisor",cell:(row)=><div className="primary-cell"><span>{row.assignedTechnicianName || "Unassigned"}</span><small>{row.supervisorName}</small></div>},{key:"dates",header:"Planned / due",cell:(row)=><div className="primary-cell"><span>{formatDate(row.plannedDate)}</span><small>{formatDate(row.dueDate)}</small></div>},{key:"priority",header:"Priority",cell:(row)=><StatusBadge value={row.priority}/>},{key:"lifecycle",header:"Lifecycle",cell:(row)=><StatusBadge value={row.lifecycleStatus}/>},{key:"overdue",header:"Timing",cell:(row)=><StatusBadge value={row.overdue ? `${row.daysOverdue} days overdue` : row.isDueToday ? "Due today" : row.isDueSoon ? "Due soon" : "On schedule"}/>},{key:"escalation",header:"Escalation",cell:(row)=>row.escalationLevel ? <StatusBadge value={`Level ${row.escalationLevel}`}/> : "—"},{key:"action",header:"",cell:(row)=><Link className="icon-button" href={`/work-orders/${row.id}`} aria-label={`View ${row.workOrderNumber}`}><Eye size={16}/></Link>}];
  return <div className="page-stack"><PageHeader eyebrow="Maintenance operations" title="Work orders" description="Track lifecycle, timing, assignment, submissions, and escalation separately."/><FilterBar onClear={() => setFilters({search:"",machineId:"",technicianId:"",supervisorId:"",lifecycleStatus:"",priority:"",plannedFrom:"",plannedTo:"",overdue:""})}><Search value={filters.search} onChange={(event)=>set("search",event.target.value)} placeholder="WO number, machine or plan…"/><Select aria-label="Machine" value={filters.machineId} onChange={(event)=>set("machineId",event.target.value)}><option value="">All machines</option>{machines.data?.items.map((item)=><option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select><Select aria-label="Technician" value={filters.technicianId} onChange={(event)=>set("technicianId",event.target.value)}><option value="">All technicians</option>{refs.technicians.data?.map((item)=><option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</Select><Select aria-label="Lifecycle" value={filters.lifecycleStatus} onChange={(event)=>set("lifecycleStatus",event.target.value)}><option value="">All lifecycle states</option>{["PLANNED","ASSIGNED","IN_PROGRESS","AWAITING_APPROVAL","APPROVED","REJECTED","CANCELLED"].map((value)=><option key={value}>{value}</option>)}</Select><Select aria-label="Priority" value={filters.priority} onChange={(event)=>set("priority",event.target.value)}><option value="">All priorities</option>{["LOW","MEDIUM","HIGH","CRITICAL"].map((value)=><option key={value}>{value}</option>)}</Select><Select aria-label="Overdue" value={filters.overdue} onChange={(event)=>set("overdue",event.target.value)}><option value="">Any timing</option><option value="true">Overdue only</option><option value="false">Not overdue</option></Select><DateControl aria-label="Planned from" value={filters.plannedFrom} onChange={(event)=>set("plannedFrom",event.target.value)}/><DateControl aria-label="Planned to" value={filters.plannedTo} onChange={(event)=>set("plannedTo",event.target.value)}/></FilterBar>{orders.isPending?<LoadingSkeleton rows={8}/>:orders.error?<ErrorState error={orders.error} onRetry={()=>orders.refetch()}/>:<><Table columns={columns} items={orders.data?.items??[]} rowKey={(row)=>row.id}/><Pagination page={orders.data?.page??page} totalPages={orders.data?.totalPages??1} totalCount={orders.data?.totalCount} onPageChange={setPage}/></>}</div>;
}
