namespace MaintainPro.Domain.Enums;

public enum NotificationType
{
    WORK_ORDER_ASSIGNED, WORK_ORDER_REASSIGNED, WORK_ORDER_DUE_SOON, WORK_ORDER_DUE, WORK_ORDER_OVERDUE, WORK_ORDER_SUBMITTED, WORK_ORDER_APPROVED, WORK_ORDER_REJECTED, ESCALATION_SUPERVISOR, ESCALATION_MANAGER
}
