namespace MaintainPro.Domain.Enums;

public enum NotificationType
{
    WORK_ORDER_ASSIGNED, WORK_ORDER_REASSIGNED, WORK_ORDER_DUE_SOON, WORK_ORDER_DUE, WORK_ORDER_OVERDUE, WORK_ORDER_SUBMITTED, WORK_ORDER_APPROVED, WORK_ORDER_REJECTED, ESCALATION_SUPERVISOR, ESCALATION_MANAGER,
    BREAKDOWN_REPORTED, BREAKDOWN_CRITICAL, BREAKDOWN_ASSIGNED,
    CORRECTIVE_SUBMITTED, CORRECTIVE_APPROVED, CORRECTIVE_REJECTED,
    CALIBRATION_60_DAY, CALIBRATION_30_DAY, CALIBRATION_7_DAY, CALIBRATION_EXPIRED,
    CALIBRATION_RENEWAL_STARTED, CALIBRATION_RENEWED
}
