"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowLeft, ArrowUp, Plus, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { z } from "zod";
import { Button, Card, Checkbox, ErrorState, Field, Input, LoadingSkeleton, PageHeader, PermissionState, Select, Tabs, Textarea } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { useAuth } from "@/features/auth/auth-provider";
import { api, errorMessage } from "@/lib/api-client";
import { useReferenceData } from "@/lib/reference-data";
import type { ChecklistTemplate, Machine, MaintenancePlan, MasterDataItem, PagedResult } from "@/types/api";

const itemSchema = z.object({ sequenceNumber: z.number(), title: z.string().trim().min(1, "Checklist title is required"), description: z.string().optional(), responseType: z.enum(["BOOLEAN", "PASS_FAIL", "NUMBER", "TEXT", "PHOTO", "CONFIRMATION"]), isMandatory: z.boolean(), unit: z.string().optional(), minimumValue: z.number().nullable().optional(), maximumValue: z.number().nullable().optional(), photoRequired: z.boolean() });
const schema = z.object({ machineId: z.string().uuid("Select a machine"), planName: z.string().trim().min(2, "Plan name is required"), maintenanceTypeId: z.string().uuid("Select a maintenance type"), priority: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]), frequencyType: z.enum(["DAILY", "WEEKLY", "MONTHLY", "DAYS", "WEEKS", "MONTHS", "QUARTERLY", "HALF_YEARLY", "YEARLY"]), frequencyValue: z.number().int().min(1, "Frequency must be at least 1"), startDate: z.string().min(1, "Start date is required"), supervisorId: z.string().uuid("Select a supervisor"), defaultTechnicianId: z.string().optional(), instructions: z.string().optional(), estimatedDurationMinutes: z.number().int().positive().nullable().optional(), photoRequired: z.boolean(), minimumPhotoCount: z.number().int().min(0), commentRequired: z.boolean(), isActive: z.boolean(), checklistName: z.string().trim().min(1, "Checklist name is required"), items: z.array(itemSchema).min(1, "Add at least one checklist item") });
type Values = z.infer<typeof schema>;
const blankItem = { sequenceNumber: 1, title: "", description: "", responseType: "BOOLEAN" as const, isMandatory: true, unit: "", minimumValue: null, maximumValue: null, photoRequired: false };
const defaults: Values = { machineId: "", planName: "", maintenanceTypeId: "", priority: "MEDIUM", frequencyType: "MONTHLY", frequencyValue: 1, startDate: new Date().toISOString().slice(0, 10), supervisorId: "", defaultTechnicianId: "", instructions: "", estimatedDurationMinutes: null, photoRequired: false, minimumPhotoCount: 0, commentRequired: false, isActive: true, checklistName: "Maintenance checklist", items: [blankItem] };

export function PlanEditor({ planId }: { planId?: string }) {
  const { hasRole } = useAuth(); const canManage = hasRole("MANAGER", "ADMIN"); const refs = useReferenceData(); const router = useRouter(); const client = useQueryClient(); const { showToast } = useToast(); const [tab, setTab] = useState("general");
  const machines = useQuery({ queryKey: ["machines", "plan-options"], queryFn: ({ signal }) => api.get<PagedResult<Machine>>("/machines?Page=1&PageSize=100&IsActive=true", signal), enabled: canManage });
  const types = useQuery({ queryKey: ["maintenance-types"], queryFn: ({ signal }) => api.get<MasterDataItem[]>("/maintenance-types?IsActive=true", signal), enabled: canManage });
  const detail = useQuery({ queryKey: ["plans", planId], queryFn: ({ signal }) => api.get<MaintenancePlan>(`/maintenance-plans/${planId}`, signal), enabled: Boolean(planId) && canManage });
  const checklist = useQuery({ queryKey: ["plans", planId, "checklist"], queryFn: ({ signal }) => api.get<ChecklistTemplate>(`/maintenance-plans/${planId}/checklist`, signal), enabled: Boolean(planId) && canManage });
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: defaults }); const { fields, append, remove, move } = useFieldArray({ control: form.control, name: "items" });
  useEffect(() => { if (!detail.data) return; form.reset({ ...defaults, ...detail.data, defaultTechnicianId: detail.data.defaultTechnicianId ?? "", instructions: detail.data.instructions ?? "", estimatedDurationMinutes: detail.data.estimatedDurationMinutes ?? null, checklistName: checklist.data?.name ?? defaults.checklistName, items: checklist.data?.items.map((item, index) => ({ ...item, sequenceNumber: index + 1, description: item.description ?? "", unit: item.unit ?? "", minimumValue: item.minimumValue ?? null, maximumValue: item.maximumValue ?? null })) ?? defaults.items }); }, [detail.data, checklist.data, form]);
  const savePlan = useMutation({ mutationFn: async (values: Values) => { const request = { machineId: values.machineId, planName: values.planName, maintenanceTypeId: values.maintenanceTypeId, priority: values.priority, frequencyType: values.frequencyType, frequencyValue: values.frequencyValue, startDate: values.startDate, supervisorId: values.supervisorId, defaultTechnicianId: values.defaultTechnicianId || null, instructions: values.instructions || null, estimatedDurationMinutes: values.estimatedDurationMinutes || null, photoRequired: values.photoRequired, minimumPhotoCount: values.minimumPhotoCount, commentRequired: values.commentRequired, isActive: values.isActive }; const plan = planId ? await api.put<MaintenancePlan>(`/maintenance-plans/${planId}`, request) : await api.post<MaintenancePlan>("/maintenance-plans", request); if (!planId) await api.put(`/maintenance-plans/${plan.id}/checklist`, { name: values.checklistName, items: values.items.map((item, index) => ({ ...item, sequenceNumber: index + 1, description: item.description || null, unit: item.unit || null })) }); return plan; }, onSuccess: (plan) => { showToast(planId ? "Plan updated" : "Plan and checklist created"); client.invalidateQueries({ queryKey: ["plans"] }); router.push(`/maintenance-plans/${plan.id}`); } });
  const publishChecklist = useMutation({ mutationFn: (values: Values) => api.put<ChecklistTemplate>(`/maintenance-plans/${planId}/checklist`, { name: values.checklistName, items: values.items.map((item, index) => ({ ...item, sequenceNumber: index + 1, description: item.description || null, unit: item.unit || null })) }), onSuccess: (created) => { showToast(`Checklist version ${created.version} published`); client.invalidateQueries({ queryKey: ["plans", planId, "checklist"] }); } });
  if (!canManage) return <PermissionState description="Only managers and administrators can create or edit maintenance plans." />;
  if ((planId && (detail.isPending || checklist.isPending)) || machines.isPending || types.isPending) return <LoadingSkeleton rows={8}/>;
  if (detail.error || checklist.error || machines.error || types.error) return <ErrorState error={detail.error ?? checklist.error ?? machines.error ?? types.error} />;
  const fieldError = form.formState.errors.items?.root?.message || form.formState.errors.items?.message;
  return <div className="page-stack"><PageHeader eyebrow="Preventive maintenance" title={planId ? "Edit maintenance plan" : "Create maintenance plan"} description={planId && checklist.data ? `Current checklist version ${checklist.data.version}. Publishing changes creates a new immutable version.` : "Define the schedule, evidence rules, assignments, and first checklist."} actions={<Link className="button button-secondary button-md" href={planId ? `/maintenance-plans/${planId}` : "/maintenance-plans"}><ArrowLeft size={16}/> Back</Link>} />
    <Tabs active={tab} onChange={setTab} tabs={[{id:"general",label:"General"},{id:"schedule",label:"Schedule"},{id:"assignment",label:"Assignment"},{id:"evidence",label:"Evidence"},{id:"instructions",label:"Instructions"},{id:"checklist",label:"Checklist builder"}]} />
    {(savePlan.error || publishChecklist.error) && <div className="form-alert" role="alert">{errorMessage(savePlan.error ?? publishChecklist.error)}</div>}
    <form className="form-stack" onSubmit={form.handleSubmit((values) => savePlan.mutateAsync(values).catch(() => undefined))} noValidate>
      {tab === "general" && <Card className="form-section"><header><h2>General</h2><p>Connect this plan to the correct asset and maintenance type.</p></header><div className="form-grid"><Field label="Plan name" required error={form.formState.errors.planName?.message}><Input {...form.register("planName")}/></Field><Field label="Machine" required error={form.formState.errors.machineId?.message}><Select {...form.register("machineId")}><option value="">Select machine</option>{machines.data?.items.map((item) => <option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select></Field><Field label="Maintenance type" required error={form.formState.errors.maintenanceTypeId?.message}><Select {...form.register("maintenanceTypeId")}><option value="">Select type</option>{types.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Priority"><Select {...form.register("priority")}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></Select></Field><Checkbox label="Active plan" {...form.register("isActive")}/></div></Card>}
      {tab === "schedule" && <Card className="form-section"><header><h2>Schedule</h2><p>Future work orders are generated from this recurrence.</p></header><div className="form-grid"><Field label="Frequency type"><Select {...form.register("frequencyType")}><option>DAILY</option><option>WEEKLY</option><option>MONTHLY</option><option>DAYS</option><option>WEEKS</option><option>MONTHS</option><option>QUARTERLY</option><option>HALF_YEARLY</option><option>YEARLY</option></Select></Field><Field label="Every" error={form.formState.errors.frequencyValue?.message}><Input type="number" min="1" {...form.register("frequencyValue", { valueAsNumber: true })}/></Field><Field label="Start date" required error={form.formState.errors.startDate?.message}><Input type="date" {...form.register("startDate")}/></Field><Field label="Estimated duration (minutes)"><Input type="number" min="1" {...form.register("estimatedDurationMinutes", { setValueAs: (value) => value === "" ? null : Number(value) })}/></Field></div></Card>}
      {tab === "assignment" && <Card className="form-section"><header><h2>Assignment</h2><p>Choose the approving supervisor and optional default technician.</p></header><div className="form-grid"><Field label="Supervisor" required error={form.formState.errors.supervisorId?.message}><Select {...form.register("supervisorId")}><option value="">Select supervisor</option>{refs.supervisors.data?.map((item) => <option key={item.id} value={item.id}>{item.employeeId} · {item.firstName} {item.lastName}</option>)}</Select></Field><Field label="Default technician"><Select {...form.register("defaultTechnicianId")}><option value="">Assign during generation</option>{refs.technicians.data?.map((item) => <option key={item.id} value={item.id}>{item.employeeId} · {item.firstName} {item.lastName}</option>)}</Select></Field></div></Card>}
      {tab === "evidence" && <Card className="form-section"><header><h2>Evidence rules</h2><p>Set completion requirements copied into generated work orders.</p></header><div className="form-grid"><Checkbox label="Photo evidence required" {...form.register("photoRequired")}/><Field label="Minimum photo count"><Input type="number" min="0" {...form.register("minimumPhotoCount", { valueAsNumber: true })}/></Field><Checkbox label="Completion comment required" {...form.register("commentRequired")}/></div></Card>}
      {tab === "instructions" && <Card className="form-section"><header><h2>Instructions</h2><p>Give technicians clear context before they start.</p></header><Field label="Plan instructions"><Textarea rows={8} {...form.register("instructions")}/></Field></Card>}
      {tab === "checklist" && <Card className="form-section checklist-builder"><header><div><h2>Checklist builder</h2><p>{planId ? `Editing version ${checklist.data?.version ?? "—"}. Published versions remain read-only in historical work.` : "Build the first checklist version."}</p></div><Button type="button" variant="secondary" onClick={() => append({ ...blankItem, sequenceNumber: fields.length + 1 })}><Plus size={16}/> Add item</Button></header><Field label="Checklist name" required error={form.formState.errors.checklistName?.message}><Input {...form.register("checklistName")}/></Field>{fieldError && <p className="field-error">{fieldError}</p>}<div className="checklist-items">{fields.map((field, index) => <Card className="checklist-item" key={field.id}><div className="checklist-sequence">{index + 1}</div><div className="checklist-fields"><Field label="Item title" required error={form.formState.errors.items?.[index]?.title?.message}><Input {...form.register(`items.${index}.title`)}/></Field><Field label="Response type"><Select {...form.register(`items.${index}.responseType`)}><option>BOOLEAN</option><option>PASS_FAIL</option><option>NUMBER</option><option>TEXT</option><option>PHOTO</option><option>CONFIRMATION</option></Select></Field><Field label="Description"><Input {...form.register(`items.${index}.description`)}/></Field><Field label="Unit"><Input {...form.register(`items.${index}.unit`)}/></Field><Field label="Minimum"><Input type="number" step="any" {...form.register(`items.${index}.minimumValue`, { setValueAs: (value) => value === "" ? null : Number(value) })}/></Field><Field label="Maximum"><Input type="number" step="any" {...form.register(`items.${index}.maximumValue`, { setValueAs: (value) => value === "" ? null : Number(value) })}/></Field><Checkbox label="Mandatory" {...form.register(`items.${index}.isMandatory`)}/><Checkbox label="Photo required" {...form.register(`items.${index}.photoRequired`)}/></div><div className="checklist-actions"><button type="button" className="icon-button" disabled={index === 0} onClick={() => move(index, index - 1)} aria-label="Move item up"><ArrowUp size={15}/></button><button type="button" className="icon-button" disabled={index === fields.length - 1} onClick={() => move(index, index + 1)} aria-label="Move item down"><ArrowDown size={15}/></button><button type="button" className="icon-button danger" disabled={fields.length === 1} onClick={() => remove(index)} aria-label="Remove checklist item"><Trash2 size={15}/></button></div></Card>)}</div>{planId && <div className="inline-action"><p>Checklist changes are saved separately so routine plan edits do not create unnecessary versions.</p><Button type="button" variant="secondary" loading={publishChecklist.isPending} onClick={form.handleSubmit((values) => publishChecklist.mutateAsync(values).catch(() => undefined))}>Publish new checklist version</Button></div>}</Card>}
      <div className="form-actions"><Link className="button button-secondary button-md" href="/maintenance-plans">Cancel</Link><Button type="submit" loading={savePlan.isPending || form.formState.isSubmitting}><Save size={16}/> {planId ? "Save plan" : "Create plan"}</Button></div>
    </form>
  </div>;
}
