"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Eye, Pencil, Plus, Power } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button, ErrorState, Field, FilterBar, Input, LoadingSkeleton, Modal, PageHeader, Pagination, Search, Select, StatusBadge, Table, type TableColumn } from "@/components/ui";
import { useToast } from "@/components/ui/toast";
import { useAuth } from "@/features/auth/auth-provider";
import { api, errorMessage, queryString } from "@/lib/api-client";
import { formatDate } from "@/lib/format";
import { lookupUser, useReferenceData } from "@/lib/reference-data";
import type { Machine, MaintenancePlan, MasterDataItem, PagedResult } from "@/types/api";

export function PlanList() {
  const { hasRole } = useAuth(); const canManage = hasRole("MANAGER", "ADMIN"); const refs = useReferenceData(); const client = useQueryClient(); const { showToast } = useToast(); const router = useRouter();
  const [filters, setFilters] = useState({ search: "", machineId: "", maintenanceTypeId: "", supervisorId: "", defaultTechnicianId: "", isActive: "true" }); const [page, setPage] = useState(1); const [duplicate, setDuplicate] = useState<MaintenancePlan>(); const [duplicateName, setDuplicateName] = useState(""); const [startDate, setStartDate] = useState("");
  const machines = useQuery({ queryKey: ["machines", "plan-options"], queryFn: ({ signal }) => api.get<PagedResult<Machine>>("/machines?Page=1&PageSize=100&IsActive=true", signal) });
  const types = useQuery({ queryKey: ["maintenance-types"], queryFn: ({ signal }) => api.get<MasterDataItem[]>("/maintenance-types?IsActive=true", signal), enabled: canManage });
  const params = queryString({ Search: filters.search, Page: page, PageSize: 20, MachineId: filters.machineId, MaintenanceTypeId: filters.maintenanceTypeId, SupervisorId: filters.supervisorId, DefaultTechnicianId: filters.defaultTechnicianId, IsActive: filters.isActive });
  const plans = useQuery({ queryKey: ["plans", filters, page], queryFn: ({ signal }) => api.get<PagedResult<MaintenancePlan>>(`/maintenance-plans${params}`, signal), placeholderData: (previous) => previous });
  const toggle = useMutation({ mutationFn: (plan: MaintenancePlan) => api.patch(`/maintenance-plans/${plan.id}/status`, { isActive: !plan.isActive }), onSuccess: () => { showToast("Plan status updated"); client.invalidateQueries({ queryKey: ["plans"] }); } });
  const duplicateMutation = useMutation({ mutationFn: () => api.post<MaintenancePlan>(`/maintenance-plans/${duplicate?.id}/duplicate`, { planName: duplicateName, startDate }), onSuccess: (plan) => { showToast("Plan duplicated"); setDuplicate(undefined); client.invalidateQueries({ queryKey: ["plans"] }); router.push(`/maintenance-plans/${plan.id}`); } });
  const update = (name: string, value: string) => { setFilters((current) => ({ ...current, [name]: value })); setPage(1); };
  const columns: TableColumn<MaintenancePlan>[] = [
    { key: "name", header: "Plan", cell: (row) => <div className="primary-cell"><strong>{row.planName}</strong><span>{row.frequencyValue} × {row.frequencyType.replaceAll("_", " ").toLowerCase()}</span></div> },
    { key: "machine", header: "Machine", cell: (row) => { const machine = machines.data?.items.find((item) => item.id === row.machineId); return machine ? <div className="primary-cell"><strong>{machine.machineCode}</strong><span>{machine.name}</span></div> : `${row.machineId.slice(0, 8)}…`; } },
    { key: "type", header: "Type", cell: (row) => types.data?.find((item) => item.id === row.maintenanceTypeId)?.name ?? `${row.maintenanceTypeId.slice(0, 8)}…` },
    { key: "assigned", header: "Technician / supervisor", cell: (row) => <div className="primary-cell"><span>{lookupUser(refs.technicians.data, row.defaultTechnicianId)}</span><small>{lookupUser(refs.supervisors.data, row.supervisorId)}</small></div> },
    { key: "next", header: "Next due", cell: (row) => formatDate(row.nextDueDate) }, { key: "priority", header: "Priority", cell: (row) => <StatusBadge value={row.priority} /> }, { key: "status", header: "Status", cell: (row) => <StatusBadge value={row.isActive} /> },
    { key: "actions", header: "Actions", className: "actions-cell", cell: (row) => <div className="table-actions"><Link className="icon-button" href={`/maintenance-plans/${row.id}`} aria-label={`View ${row.planName}`}><Eye size={16}/></Link>{canManage && <><Link className="icon-button" href={`/maintenance-plans/${row.id}/edit`} aria-label={`Edit ${row.planName}`}><Pencil size={16}/></Link><button className="icon-button" aria-label={`Duplicate ${row.planName}`} onClick={() => { setDuplicate(row); setDuplicateName(`${row.planName} copy`); setStartDate(row.startDate); }}><Copy size={16}/></button><button className="icon-button" aria-label={`${row.isActive ? "Deactivate" : "Activate"} ${row.planName}`} onClick={() => toggle.mutate(row)}><Power size={16}/></button></>}</div> },
  ];
  return <div className="page-stack"><PageHeader eyebrow="Preventive maintenance" title="Maintenance plans" description="Define recurring maintenance, assignments, evidence, and versioned checklists." actions={canManage && <Link className="button button-primary button-md" href="/maintenance-plans/new"><Plus size={16}/> Add plan</Link>} /><FilterBar onClear={() => setFilters({ search: "", machineId: "", maintenanceTypeId: "", supervisorId: "", defaultTechnicianId: "", isActive: "" })}><Search value={filters.search} onChange={(event) => update("search", event.target.value)} placeholder="Search plan or machine…"/><Select aria-label="Machine" value={filters.machineId} onChange={(event) => update("machineId", event.target.value)}><option value="">All machines</option>{machines.data?.items.map((item) => <option key={item.id} value={item.id}>{item.machineCode} · {item.name}</option>)}</Select><Select aria-label="Maintenance type" value={filters.maintenanceTypeId} onChange={(event) => update("maintenanceTypeId", event.target.value)}><option value="">All types</option>{types.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Technician" value={filters.defaultTechnicianId} onChange={(event) => update("defaultTechnicianId", event.target.value)}><option value="">All technicians</option>{refs.technicians.data?.map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</Select><Select aria-label="Status" value={filters.isActive} onChange={(event) => update("isActive", event.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></Select></FilterBar>{plans.isPending ? <LoadingSkeleton rows={8}/> : plans.error ? <ErrorState error={plans.error} onRetry={() => plans.refetch()}/> : <><Table columns={columns} items={plans.data?.items ?? []} rowKey={(row) => row.id}/><Pagination page={plans.data?.page ?? page} totalPages={plans.data?.totalPages ?? 1} totalCount={plans.data?.totalCount} onPageChange={setPage}/></>}
  <Modal open={Boolean(duplicate)} title="Duplicate maintenance plan" onClose={() => setDuplicate(undefined)} footer={<><Button variant="secondary" onClick={() => setDuplicate(undefined)}>Cancel</Button><Button loading={duplicateMutation.isPending} disabled={!duplicateName.trim() || !startDate} onClick={() => duplicateMutation.mutate()}>Duplicate plan</Button></>}><div className="form-stack compact"><Field label="New plan name" required><Input value={duplicateName} onChange={(event) => setDuplicateName(event.target.value)}/></Field><Field label="New start date" required><Input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)}/></Field>{duplicateMutation.error && <p className="field-error">{errorMessage(duplicateMutation.error)}</p>}</div></Modal></div>;
}
