import { screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { jsonResponse, renderWithProviders } from "@/test/test-utils";
import { PlanEditor } from "./plan-editor";
import { PlanList } from "./plan-list";

vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn(), replace: vi.fn() }) }));
vi.mock("@/features/auth/auth-provider", () => ({ useAuth: () => ({ hasRole: (...roles: string[]) => roles.includes("MANAGER") }) }));
const ids = { machine: "11111111-1111-1111-1111-111111111111", type: "22222222-2222-2222-2222-222222222222", tech: "33333333-3333-3333-3333-333333333333", supervisor: "44444444-4444-4444-4444-444444444444" };
const machine = { id: ids.machine, machineCode: "MC-1", name: "Mixer", status: "Operational", criticality: "Medium", calibrationRequired: false, preventiveMaintenanceRequired: true, isActive: true, createdAt: "", updatedAt: "", currentCalibrationStatus: "NOT_REQUIRED", renewalInProgress: false };
const plan = { id: "55555555-5555-5555-5555-555555555555", machineId: ids.machine, planName: "Monthly inspection", maintenanceTypeId: ids.type, priority: "MEDIUM", frequencyType: "MONTHLY", frequencyValue: 1, startDate: "2026-09-01", nextDueDate: "2026-10-01", defaultTechnicianId: ids.tech, supervisorId: ids.supervisor, photoRequired: false, minimumPhotoCount: 0, commentRequired: false, isActive: true, createdByUserId: "u", createdAt: "", updatedAt: "" };
function mockApi(){return vi.spyOn(globalThis,"fetch").mockImplementation((input)=>{const url=String(input);if(url.includes("/departments"))return jsonResponse([]);if(url.includes("/locations"))return jsonResponse([]);if(url.includes("/machine-categories"))return jsonResponse([]);if(url.includes("/users/technicians"))return jsonResponse([{id:ids.tech,employeeId:"T1",firstName:"Anu",lastName:"Jose"}]);if(url.includes("/users/supervisors"))return jsonResponse([{id:ids.supervisor,employeeId:"S1",firstName:"Ravi",lastName:"Nair"}]);if(url.includes("/maintenance-types"))return jsonResponse([{id:ids.type,name:"Inspection",isActive:true}]);if(url.includes("/maintenance-plans"))return jsonResponse({items:[plan],page:1,pageSize:20,totalCount:1,totalPages:1});if(url.includes("/machines?"))return jsonResponse({items:[machine],page:1,pageSize:100,totalCount:1,totalPages:1});return jsonResponse({})})}
describe("maintenance plans",()=>{beforeEach(()=>vi.restoreAllMocks());it("renders the plan list",async()=>{mockApi();renderWithProviders(<PlanList/>);expect(await screen.findByText("Monthly inspection")).toBeInTheDocument();expect(screen.getAllByText("Inspection")).toHaveLength(2)});it("adds and reorders checklist builder rows",async()=>{mockApi();renderWithProviders(<PlanEditor/>);await userEvent.click(await screen.findByRole("tab",{name:"Checklist builder"}));expect(screen.getAllByLabelText(/Item title/)).toHaveLength(1);await userEvent.click(screen.getByRole("button",{name:/add item/i}));expect(screen.getAllByLabelText(/Item title/)).toHaveLength(2);expect(screen.getAllByRole("button",{name:"Move item up"})[1]).toBeEnabled()})});
